// kelimeler.js
const kelimeler = [
  { eski: "Âbâ", yeni: "1.atalar, babalar, pederler 2.yünden yapılmış kaba kumaş, bol giyimli bir libas, elbise." },
  { eski: "Âbânî", yeni: "ipekten, sarıya çalar bir renkte dallı nakışlarla işlenmiş bir tür beyaz kumaş." },
  { eski: "Abes", yeni: "boş, anlamsız, gayesiz, saçma." },
  { eski: "Ab-ı rûy", yeni: "yüzsuyu, şeref, haysiyet, namus." },
  { eski: "A’dâd", yeni: "adetler, sayılar." },
  { eski: "Adale", yeni: "kas, kaslar." },
  { eski: "Adem", yeni: "yokluk, hiçlik, olmama, bulunmama" },
  { eski: "Adû", yeni: "düşman." },
  { eski: "Afâk", yeni: "ufuklar, dış alemler; taraflar, yönler." },
  { eski: "Ağniyâ", yeni: "zenginler, ganiler." },
  { eski: "Âğûş", yeni: "kucak, sığınılacak yer." },
  { eski: "Ağyâr", yeni: "başkaları, yabancılar, düşmanlar, rakipler." },
  { eski: "Âhâd", yeni: "birler, birden dokuza kadar olan sayılar." },
  { eski: "Ahcâr", yeni: "taşlar." },
  { eski: "Ahenîn", yeni: "demirden, demir gibi; çok kuvvetli, pek sağlam." },
  { eski: "Aheste", yeni: "yavaş, ağır, usul." },
  { eski: "Ahfâd", yeni: "torunlar, hafidler." },
  { eski: "Ahiren", yeni: "sonradan, son olarak, geçenlerde, son zamanlarda." },
  { eski: "Ahlâf", yeni: "gelecek nesiller." },
  { eski: "Ahlât", yeni: "karıştırılmaya elverişli, çok karıştırılabilir; salgılar." },
  { eski: "Ahrâr", yeni: "hür kişiler, özgürler, esir ve köle olmayanlar." },
  { eski: "Ahyâ", yeni: "diriler, canlılar." },
  { eski: "Akabât", yeni: "1. Korkunç durumlar, tehlikeli anlar. 2. Tehlikeli geçitler, sarp yollar." },
  { eski: "Akdâh", yeni: "kadehler." },
  { eski: "Akdes", yeni: "en mukaddes, en mübarek, en kutsal." },
  { eski: "Âkil", yeni: "yiyen, yiyici." },
  { eski: "Akîm", yeni: "neticesiz, beyhude, sonuçsuz; kısır, verimsiz." },
  { eski: "Aksâ", yeni: "en son, uzak, en uzak." },
  { eski: "Aktâr", yeni: "1. Her taraf, her yer, taraflar, yöreler. 2. Güzel kokular taciri, baharatçı. 3. Ecza, ilaç satan adam. 4. Çaplar, dairenin merkezinden geçen doğru hatlar." },
  { eski: "Akvâl", yeni: "sözler, kaviller, konuşmalar." },
  { eski: "Akvâm", yeni: "kavimler, ırklar, milletler." },
  { eski: "Âlâm", yeni: "elemler, kederler, acılar, üzüntüler." },
  { eski: "Amâde", yeni: "hazır, hazırlanmış." },
  { eski: "A’mâk", yeni: "derinlikler." },
  { eski: "Amâl", yeni: "ameller, işler; emeller, arzular, istekler." },
  { eski: "Amel-mânde", yeni: "iş göremez durumda olan." },
  { eski: "Âmennâ", yeni: "inandık, iman ettik." },
  { eski: "Amîk", yeni: "derin." },
  { eski: "Amûd", yeni: "sütun, direk." },
  { eski: "An-karib", yeni: "yakından, en kısa zamanda, çok zaman geçmeden." },
  { eski: "Ananât", yeni: "ananeler, gelenekler." },
  { eski: "Anâsır", yeni: "unsurlar, elementler, elemanlar." }
  { eski: "Ârâ", yeni: "1. Oylar, reyler, fikirler. 2. süsleyen, bezeyen. 3. mıntıka, bölge, komşuluk. 4. avlu. 5. çıplaklık." },
{ eski: "Arâkiyye", yeni: "Dervişlerin giydikleri yünden yapılmış bir çeşit külah; ter çeken başlık, terlik." },
{ eski: "Ârâm", yeni: "1. Durma, dinlenme, sükun, karar. 2. Rahat, huzur, istirahat." },
{ eski: "Aramgâh", yeni: "Dinlenme yeri, mezar." },
{ eski: "Arsenik", yeni: "Bir tür element." },
{ eski: "Arz", yeni: "1. Toprak, yeryüzü, dünya, zemin. 2. Memleket, ülke. 3. Genişlik, en. 4. Sunma, arz etme." },
{ eski: "Âsâr", yeni: "Eserler, izler, nişanlar." },
{ eski: "Asûd", yeni: "Arslanlar, yiğitler." },
{ eski: "Âsüman", yeni: "Gökyüzü, sema, felek, gök kubbe." },
{ eski: "Âşinâ", yeni: "Bildik, tanıdık; bilen, tanıyan." },
{ eski: "Aşiyân", yeni: "Yuva, ev, mesken, ikametgâh, kuş yuvası." },
{ eski: "Aşûb", yeni: "Kargaşa, karıştırıcı, karıştıran." },
{ eski: "Ateh", yeni: "Bunama, bunaklık." },
{ eski: "Âti", yeni: "Gelecek, ilerideki, aşağıdaki; inatçı, kalın kafalı, sert başlı." },
{ eski: "Attâr", yeni: "Baharatçı, aktar, güzel koku satan adam." },
{ eski: "Avâlim", yeni: "Alemler, dünyalar, cihanlar." },
{ eski: "Âyât", yeni: "Ayetler, menziller, mekânlar." },
{ eski: "Ayyuk", yeni: "1. Gökyüzünün pek yüksek yeri. 2. Samanyolunun daima sağ tarafında olan çok parlak ve uzak bir yıldız." },
{ eski: "Âzâde", yeni: "Hür, özgür, serbest, bağlardan kurtulmuş." }
{ eski: "Ba’s", yeni: "1. Dirilme, diriltme, diriliş, ihya. 2. Gönderme, gönderilme, yollama." },
{ eski: "Bâb", yeni: "1. Kapı, bölüm, kısım, fasıl; mevzu, konu. 2. Bektaşi şeyhi, manevi rehber, şeyh. 3. Hayır, uğur; ata, ecdad. 4. Layık, uygun, elverişli, münasip." },
{ eski: "Bâd", yeni: "1. Rüzgâr, yel; soluk, nefes. 2. Defa, kez; yük, olsun." },
{ eski: "Bâde", yeni: "Şarap, içki; kadeh." },
{ eski: "Bâdî", yeni: "1. Sebep, sebep olan, yol açan; halk eden, hâlık, yaratan. 2. Geçici, havaya veya rüzgâra ait, zahir ve aşikâr olan." },
{ eski: "Badîye", yeni: "Çöl, sahra; kır, ova." },
{ eski: "Bâh", yeni: "Şehvet, cinsel güç." },
{ eski: "Bahr", yeni: "1. Deniz, büyük göl veya nehir. 2. Âlim, çok bilen, iyi kimse. 3. Yarmak, yırtmak; çok yürüyen at, deve hastalığı." },
{ eski: "Bahr-i ahmer", yeni: "Kızıldeniz." },
{ eski: "Bahs-i dûradûr", yeni: "Uzayıp giden mevzu." },
{ eski: "Bâlâ", yeni: "Üst, yukarı, yüksek, yüce." },
{ eski: "Bâr", yeni: "1. Yük, zahmet, eziyet, ağırlık. 2. Yemiş, meyve. 3. Yağdıran, serpen, döken. 4. Defa, kez, kere; izin, kale duvarı; Allah." },
{ eski: "Bârân", yeni: "Yağmur, rahmet." },
{ eski: "Bargâh", yeni: "Yüksek huzur, padişah huzuru, otağ, padişah divanhanesi; dua edilen yer." },
{ eski: "Bârû", yeni: "Sur, kale duvarı, burç, hisar burcu, sığınak." },
{ eski: "Ba'sü ba'de'l-mevt", yeni: "Ölümden sonra diriliş." },
{ eski: "Bâzîçe", yeni: "Oyuncak, eğlence." },
{ eski: "Bedâyi", yeni: "Eşi benzeri olmayan güzellikler." },
{ eski: "Bedi'", yeni: "Güzel, eşsiz güzel, benzersiz, beğenilen, yepyeni, eşi ve benzeri olmayan." },
{ eski: "Bedî", yeni: "Benzersiz güzel, üstün, özgün." },
{ eski: "Bedîhî", yeni: "İspat gerektirmeyecek kadar açık, apaçık, aşikâr, kuşkusuz." },
{ eski: "Bedreka", yeni: "Kılavuz, uğurlama, yolcu etme." },
{ eski: "Behâim", yeni: "Hayvanlar, Suriye’de bir sıradağ." },
{ eski: "Behîmî", yeni: "Hayvanca, hayvani, hayvana yakışır tarzda, hayvanlık." },
{ eski: "Beht", yeni: "Şaşkınlık, hayranlık; yalan söylemek, ansızın bir şeyi almak." },
{ eski: "Bekâ", yeni: "Kalıcılık, devamlılık, ebedilik, ölmezlik." },
{ eski: "Beliyyât", yeni: "Belalar, gamlar, felaketler, kederler, sıkıntılar." },
{ eski: "Benân", yeni: "Parmaklar, parmak uçları." },
{ eski: "Benât", yeni: "Kızlar, bebekler." },
{ eski: "Bendegân", yeni: "Padişahın hizmetindekiler, kullar, hizmetliler, köleler." },
{ eski: "Ber", yeni: "1. Üzere, üzerine, yukarı. 2. Göğüs, sine, bağır, sadır. 3. Yan, taraf; yaprak, varak; nakil, götürücü; meyve." },
{ eski: "Berâhîn", yeni: "Deliller, kanıtlar, şahitler." },
{ eski: "Berceste", yeni: "1. Seçkin, seçme, sağlam ve latif. 2. Zahmetsizce hatıra geliveren ve çok kıymetli olan söz, iyi mısra." },
{ eski: "Berdâr", yeni: "Asılmış, yukarı kaldırılmış; tutucu, itaat ettirici; meyveli, meyve verici olan." },
{ eski: "Berf", yeni: "Kar." },
{ eski: "Berhâne", yeni: "Eskiyip harap olmuş konak, ev." },
{ eski: "Berhudâr", yeni: "Mutlu, saadete erişen, selamette." },
{ eski: "Berîn", yeni: "1. Çok yüksek, en yüce, yüksek, yüce. 2. Yarık, yırtık, delik." },
{ eski: "Berk", yeni: "1. Katı, sert, sağlam. 2. Şimşek, yıldırım, parıltı, kıvılcım, şimşek çakması, parlama. 3. Zinetlenme, süslenme. 4. Göğüs, sadır; yaprak." },
{ eski: "Berk-i nigâh", yeni: "Şimşek (gibi) bakış." },
{ eski: "Bermu’tâd", yeni: "Alışıldığı üzere, her zamanki gibi." },
{ eski: "Bernâme", yeni: "Mektup başlığı, zarfın üzerindeki adres." },
{ eski: "Berzede", yeni: "Biriktirilmiş, toplanılmış, bir araya getirilmiş." },
{ eski: "Besîm", yeni: "Güleryüz’ü, güleç." },
{ eski: "Beşâret", yeni: "Müjde, muştu, iyi haber, müjdeleme." },
{ eski: "Beşuş", yeni: "Güleryüzlü, şen." },
{ eski: "Bevad", yeni: "Mahvolma, yok olma." },
{ eski: "Beyâbân", yeni: "Çöl, sahra, kır." },
{ eski: "Beyyinât", yeni: "Deliller, mucizeli açık ayetler, açık ve belli şeyler." },
{ eski: "Beyzâ", yeni: "1. Beyaz, bembeyaz, parlak; yumurta. 2. Afet, bela, musibet. 3. Demir başlık, demirden savaşçı başlığı." },
{ eski: "Bezl", yeni: "Cömertçe vermek, bol bol vermek, esirgemeden vermek." },
{ eski: "Bezm", yeni: "1. Sohbet meclisi, eğlence meclisi, içki meclisi, muhabbet yeri. 2. Yayın kirişini çekip sonra salıverme. 3. Bir şeyi diş ucuyla ısırma." },
{ eski: "Bî-aram", yeni: "Durup dinlenmeme." },
{ eski: "Bîdâr", yeni: "Uyanık, uykusuz, uyumayan." },
{ eski: "Bidâyet", yeni: "Başlangıç, başlama; ilk önce, ilk olarak." },
{ eski: "Bîhûş (et-)", yeni: "Aklını başından almak." },
{ eski: "Bîhûş", yeni: "Akılsız, şaşkın, sersem." },
{ eski: "Bi-insaf", yeni: "İnsafsız, acımasız." },
{ eski: "Bîkes", yeni: "Kimsesiz." },
{ eski: "Bilfarz", yeni: "Farz edelim ki, diyelim ki, varsaymakla, olduğunu kabul ederek." },
{ eski: "Bimâr", yeni: "Hasta." },
{ eski: "Bî-meâl", yeni: "Anlamsız, manasız." },
{ eski: "Bîn", yeni: "Gören anlamında son ek." },
{ eski: "Bina", yeni: "Göz, gören, görücü; ev, yapı, bina etme, dayandırma." },
{ eski: "Bî-payân", yeni: "Sınırsız, sonsuz." },
{ eski: "Bister", yeni: "Yatak, döşek." },
{ eski: "Bîtâb", yeni: "Güçsüz, yorgun, takatsiz." },
{ eski: "Bî-tenâhi", yeni: "Sonsuz, tükenmez." },
{ eski: "Bî-vâye", yeni: "Nasipsiz, kısmetsiz, mahrum." },
{ eski: "Bî-zar", yeni: "Bıkmış, usanmış, bezginlik." },
{ eski: "Bû'd", yeni: "Uzaklık, mesafe, aralık, boyut." },
{ eski: "Bûd", yeni: "Varlık, uzaklık." },
{ eski: "Buhayre", yeni: "Göl, küçük deniz." },
{ eski: "Buk’a", yeni: "Ülke, yer, diyar, yer parçası, boş ve ıssız yer; sağlam ve büyük bina." },
{ eski: "Burûc", yeni: "Burçlar." },
{ eski: "Büd u nebüd", yeni: "Var yok, oldu olmadı." },
{ eski: "Büka", yeni: "Ağlama." },
{ eski: "Bülend", yeni: "Yüce, yüksek, büyük." },
{ eski: "Bünyâd (kur-)", yeni: "Temel atmak." },
{ eski: "Bünyâd", yeni: "Temel, kök, yapı, bina." },
{ eski: "Bünyân", yeni: "Bina, yapı, duvar, saray." },
{ eski: "Bürehne", yeni: "Açık, yalın, çıplak." }
{ eski: "Cahim", yeni: "Cehennem, cehennemin dördüncü tabakası." },
{ eski: "Cahîmî", yeni: "Cehennem gibi." },
{ eski: "Câmedân", yeni: "Gardrop." },
{ eski: "Câmid", yeni: "Cansız, donmuş, donuk, hareketsiz, ruhsuz." },
{ eski: "Câri", yeni: "Akan, akıcı; geçerli, yürürlükte, yürüyen." },
{ eski: "Câvidân", yeni: "Ebedi, sonsuz, kalıcı." },
{ eski: "Cây", yeni: "Yer, makam, mevki; değer, layık." },
{ eski: "Cebânet", yeni: "Korkaklık, ürkeklik." },
{ eski: "Ceberut", yeni: "Azamet, büyüklük, hakimlik; baskı, zorlama." },
{ eski: "Cebin", yeni: "1. Alın. 2. Korkak, cesaretsiz, yüreksiz." },
{ eski: "Cebin-i sîmîn", yeni: "Gümüşe benzer alın, gümüş gibi alın." },
{ eski: "Cebri", yeni: "Zoraki, zorla, zorunlu olarak." },
{ eski: "Ced", yeni: "Ata, dede." },
{ eski: "Cedel-gâh", yeni: "Mücadele yeri, dünya." },
{ eski: "Cefa-dide", yeni: "Cefa görmüş, cefa çekmiş." },
{ eski: "Celâdet", yeni: "Yiğitlik, kahramanlık, bahadırlık." },
{ eski: "Celî", yeni: "Belli, açık, aşikar, meydanda, parlak." },
{ eski: "Cenâh", yeni: "Kanat, taraf, yan, yön, kısım; kol, pazu." },
{ eski: "Cenub", yeni: "Güney." },
{ eski: "Cerh", yeni: "Yaralama, yaralatma, çürütme, yara." },
{ eski: "Ceride", yeni: "Gazete, tutanak; yalnız, tenha." },
{ eski: "Ceriha", yeni: "Yara." },
{ eski: "Cevâmî", yeni: "Toplayıcı olan şeyler." },
{ eski: "Cevelan", yeni: "Dolaşma, gezme, gezinti." },
{ eski: "Cevelan-gâh", yeni: "Dolaşma yeri, gezinme yeri, gezip dolaşılan yer." },
{ eski: "Cevf", yeni: "İç, iç kısım, oyuk, çukur, boşluk; orta, yarı." },
{ eski: "Cevv", yeni: "Hava boşluğu, gök, yer ile gök arası, gök boşluğu." },
{ eski: "Ceyb", yeni: "Cep, yaka." },
{ eski: "Cibah", yeni: "Cepheler, alınlar." },
{ eski: "Cibal", yeni: "Dağlar." },
{ eski: "Cibal-i velveledâr", yeni: "Sesli dağlar, gürültülü dağlar." },
{ eski: "Cibilli", yeni: "Yaratılıştan, mayadan, soydan; huy, tabiat." },
{ eski: "Cidâl", yeni: "Mücadele, kavga, çekişme, cenk, muharebe, savaş." },
{ eski: "Cidâr", yeni: "Duvar." },
{ eski: "Cife", yeni: "Leş, ölü hayvan, kokmuş et." },
{ eski: "Cihâz", yeni: "Çeyiz, alet, edevat, aygıt, sistem; organ, duyu." },
{ eski: "Cud", yeni: "Cömertlik, eli açık olmak." },
{ eski: "Cuş", yeni: "Coşma, kaynama." },
{ eski: "Cuşiş", yeni: "Coşkunluk, coşma, coşku." },
{ eski: "Cuy", yeni: "Akarsu, ırmak, çay; arayan, arama." },
{ eski: "Cuybar", yeni: "Akarsu, ırmak, nehir, dere, çay." },
{ eski: "Cüdâ", yeni: "Uzak kalmak, ayrı düşmek, ayrı, ayrılmış, ayrılık." },
{ eski: "Cündi", yeni: "Sipahi, süvari, usta binici, ata iyi binen." },
{ eski: "Cünun", yeni: "Delilik, cinnet, delirmek." },
{ eski: "Cür’a", yeni: "Bir yudumluk su, içim, yudum." },
{ eski: "Çâk", yeni: "1. Yırtmak, yırtık, çatlak, yarık, yırtmaç. 2. İyi, güzel, sıhhatli, şişman." },
{ eski: "Çakşır", yeni: "1. İnce kumaştan yapılan uzun bir çeşit şalvar. 2. Kuşların ayağındaki tüy." },
{ eski: "Çalâk", yeni: "Çevik, atik, kıvrak, yerinde duramayan, çabuk." },
{ eski: "Çerâğ", yeni: "Kandil, lamba, mum, çıra." },
{ eski: "Çin", yeni: "Kıvrım, kırışık, büklüm, buruşukluk." }
{ eski: "Dalkavuk", yeni: "Çıkar ve yarar beklediği ya da kendisinden çıkar sağladığı kimselere makam ve durumca büyüklere karşı saygı ve hayranlık göstererek yaranmak isteyen kimse." },
{ eski: "Damǎn", yeni: "Bir şeyi üstlenme, taahhüt ve garanti etme." },
{ eski: "Dani", yeni: "Kişiler nezdinde doğacak zararlardan sorumlu olacağını, hakkında hukuki ve cezai işlem yapılacağını peşinen kabul eden kimse. Hor, zelil." },
{ eski: "Dar ü divar", yeni: "Yer, ülke, mekân." },
{ eski: "Daraban", yeni: "Vurma, vuruş, çarpış, çarpıntı." },
{ eski: "Daye", yeni: "Çocuk hizmetçisi, çocuğa süt veren dadı, mürebbi, süt anne, çocuk bakıcısı." },
{ eski: "Dehen", yeni: "Ağız." },
{ eski: "Dehhaşe", yeni: "Çok korkunç, dehşetli." },
{ eski: "Dehr", yeni: "Dünya, devir, çağ, çok uzun zaman." },
{ eski: "Dehşet", yeni: "Bir tehlike ya da korkunç bir şey karşısında duyumsanan ürküntü, büyük korku." },
{ eski: "Delâlet", yeni: "Deliller, kanıtlar." },
{ eski: "Dem", yeni: "Kan, soluk, ağız, nazar, an, vakit, saat." },
{ eski: "Demâdem", yeni: "Zaman zaman, her vakit, daima, her an." },
{ eski: "Deni", yeni: "Dünyaya ait, fani ve geçici." },
{ eski: "Dereke", yeni: "Seviye, aşağı derece, gitgide alçalan durumların her biri." },
{ eski: "Derun", yeni: "İçyüz, iç taraf, kalp, gönül." },
{ eski: "Derya", yeni: "Deniz." },
{ eski: "Dest", yeni: "El, (çoğulu: düşüt) dört bucaklı yastık ve elbise." },
{ eski: "Destâr", yeni: "Sikke’ye sarılan sargı, mevlevilikte sarık." },
{ eski: "Destar", yeni: "Eskimiş sarık, halk ağzında örtü." },
{ eski: "Desti", yeni: "Testi." },
{ eski: "Deva", yeni: "Hastalığı iyileştirici nesne, ilaç; çözüm, çare." },
{ eski: "Devahi", yeni: "Felaketler, büyük afetler, kazalar, üstün zekalılar." },
{ eski: "Devair", yeni: "Daireler." },
{ eski: "Deverân", yeni: "Dolaşma, dönme, dolaşım." },
{ eski: "Devr-i istibdad", yeni: "Baskı dönemi." },
{ eski: "Devr-i istila", yeni: "İstila zamanı." },
{ eski: "Deyyar", yeni: "Manastır sahibi, biri, bir kimse, fert." },
{ eski: "Didar", yeni: "Yüz, çehre, göz, görüş kuvveti." },
{ eski: "Dide", yeni: "Göz/görmüş, görülmüş." },
{ eski: "Didinmek", yeni: "Hiç durmadan, kendini yıpratırcasına çalışmak, çalışıp çabalamak." },
{ eski: "Dil-hah", yeni: "Gönlün isteği, arzusu." },
{ eski: "Dilber", yeni: "Gönül alan güzel sevgili." },
{ eski: "Dil-nişin", yeni: "Gönülde yer tutan; latif, hoş." },
{ eski: "Dimağ", yeni: "Akıl, beyin." },
{ eski: "Din-i fıtri", yeni: "İnsanın tabiatına uygun din, İslam." },
{ eski: "Din-i mubin", yeni: "İslam dini." },
{ eski: "Duhât", yeni: "Zekiler, dâhiler." },
{ eski: "Dur", yeni: "Uzak kalmak." },
{ eski: "Dümbelek", yeni: "Ağzında deri gerilmiş dipsiz bir çömlek biçiminden darbukaya benzeyen, alaturka müzikte tempo tutmaya yarayan el ile vurularak çalınan bir tür çalgı." },
{ eski: "Düra dür", yeni: "Uzun uzadıya, uzaktan uzağa; durmaksızın." },
{ eski: "Dürdane-i ismet", yeni: "Temizlik incisi." },
{ eski: "Düstur", yeni: "Genel kural, nizam." },
{ eski: "Düşun", yeni: "Dış evrenin kişinin zihninde yansıması." }
{ eski: "Eb'ad", yeni: "Çok uzak." },
{ eski: "Ebkem", yeni: "Dilsiz." },
{ eski: "Ecdat", yeni: "Geçmişteki büyükler, atalar ve dedeler." },
{ eski: "Ecir", yeni: "Bir işi yapmak için kendi kuvvetini veya san'atını kirâya veren, çalışan kimse, işçi." },
{ eski: "Ecnam", yeni: "Son, işin sonu; mecaz: gelecek." },
{ eski: "Ecza", yeni: "Tek parça, kısım, birimler, unsurlar." },
{ eski: "Edvar", yeni: "Devirler, dönemler." },
{ eski: "Efkan", yeni: "Bağırıp çağıran." },
{ eski: "Efkâr", yeni: "Fikirler, kaygı, tasa, üzüntü ve sıkıntı." },
{ eski: "Eflaka", yeni: "Göklere." },
{ eski: "Efrâd", yeni: "Fertler, bireyler ve şahıslar." },
{ eski: "Ekseriyyet", yeni: "Çoğunluk, çokluk." },
{ eski: "Ekvan", yeni: "Varlıklar." },
{ eski: "Elhasıl", yeni: "Sonuç olarak." },
{ eski: "Elim izmihlal", yeni: "Acı yok oluş." },
{ eski: "Elvah", yeni: "Levhalar, portler, tablolar." },
{ eski: "Elzem", yeni: "Gerekli." },
{ eski: "Emel", yeni: "Gönülde yaşatılan ve gelecekte gerçekleşmesi istenen şey, istek, arzu." },
{ eski: "Emin tarık", yeni: "Güvenilir yol." },
{ eski: "Emvac-ı berfu baran", yeni: "Yağmur ve kar dalgaları." },
{ eski: "Emvac", yeni: "Dalgalar." },
{ eski: "Emvat", yeni: "Ölüler." },
{ eski: "Enbiye", yeni: "Nebiler, peygamberler." },
{ eski: "Encüm", yeni: "Yıldızlar." },
{ eski: "Encümen", yeni: "Cemiyet, meclis." },
{ eski: "Endaze", yeni: "Eskiden kullanılan 65 cm boyunda bir uzunluk ölçüsü." },
{ eski: "Endülüs", yeni: "711-1492 arasındaki Müslümanlığın etkisi altında bulunan bölgelere verilen isim." },
{ eski: "Enfes", yeni: "Putlar." },
{ eski: "Enfiye", yeni: "Toz haline getirilmiş tütünün burun deliklerine çekilerek tüketicide nefes yoluyla fizyolojik etki yapan yabani bir tütün çeşidi." },
{ eski: "Engin", yeni: "Açık deniz; çok geniş, iyi." },
{ eski: "Enin-i istimat", yeni: "Yardım iniltisi." },
{ eski: "Enin", yeni: "İnilti, feryatlar." },
{ eski: "Enini muhtazarı", yeni: "Ölümü bekleyen." },
{ eski: "Enini ruh", yeni: "Ruhun inleyişi." },
{ eski: "Enkaz-ı tarumar beşer", yeni: "Darmadağın." },
{ eski: "Enkaz-i beşer", yeni: "İnsan yığını." },
{ eski: "Ensar", yeni: "Medine yerlileri; hicret eden Mekkelilere yardım ederler." },
{ eski: "Envar", yeni: "Nurlar, ışıklar, aydınlıklar; maddi veya manevi karanlıkta kurtulmaya vasıtalar olanlar." },
{ eski: "Epsar", yeni: "Farkında olan gözler." },
{ eski: "Erbab", yeni: "İşini iyi bilen." },
{ eski: "Erkan", yeni: "Bir toplumun önde gelenleri, söz sahipleri ve büyükler, üstler." },
{ eski: "Ervah", yeni: "Ruhlar." },
{ eski: "Esaret", yeni: "Kölelik, tutsallık ve esirlik." },
{ eski: "Esbab", yeni: "Gerektirici sebepler, gerekçeler." },
{ eski: "Escad", yeni: "Cesetler." },
{ eski: "Esef et-", yeni: "Üzülmek." },
{ eski: "Eşbah", yeni: "Uzaktan görülen karartılar ve hayaller; şahıslar, cisimler, benzerler." },
{ eski: "Eşed", yeni: "Şiddetli." },
{ eski: "Eşhas", yeni: "Kişiler, şahıslar." },
{ eski: "Eşkâli", yeni: "Şekiller." },
{ eski: "Eşvak", yeni: "Şiddetli arzular, istekler." },
{ eski: "Etfâl", yeni: "Çocuklar." },
{ eski: "Etradı", yeni: "Şahıslar, fertler." },
{ eski: "Evamir", yeni: "Emirler." },
{ eski: "Evellce", yeni: "Önceleri, eskileri." },
{ eski: "Evham", yeni: "Temelsiz kaygılar, kuruntular ve kuşkular." },
{ eski: "Evkaf", yeni: "Vakıflar müdürlüğü." },
{ eski: "Evvel", yeni: "Önce." },
{ eski: "Evvela", yeni: "İlk iş olarak, ilkin, ilk önce." },
{ eski: "Eyer", yeni: "Binicinin rahat olmasını sağlamak için binek atlarının sırtına konulan, biçim ve tip yönünden türleri bulunan nesne." },
{ eski: "Eytam", yeni: "Yetimler." },
{ eski: "Eyyami", yeni: "Günler." },
{ eski: "Ezeli", yeni: "Başlangıcı olmayan, öncesiz, eski." }
{ eski: "Faide", yeni: "Fayda, kazanç, kar, yararlılık." },
{ eski: "Fârûk", yeni: "Hz. Ömer'in lakabı; Arapça 'fark' kökünden türemiş, 'iki nesnenin arasını ayırmak' anlamında." },
{ eski: "Fasıl", yeni: "Bölüm." },
{ eski: "Fasid", yeni: "Bozuk." },
{ eski: "Faslü’l-hitab", yeni: "Seslenme bölümü." },
{ eski: "Fatin", yeni: "Işık." },
{ eski: "Fazıl", yeni: "Değerli, erdemli." },
{ eski: "Feca’atle", yeni: "İçler acısı." },
{ eski: "Fecayi", yeni: "Musibet." },
{ eski: "Fecr", yeni: "Şafak, tan ağarması." },
{ eski: "Fecr-i nazan", yeni: "Nazlı şafak." },
{ eski: "Fedai", yeni: "Her tehlikeyi göze alan, ülkü yolunda canını esirgemeyen kimse." },
{ eski: "Felah", yeni: "Kurtuluş." },
{ eski: "Fenni", yeni: "Yöntemine göre yapılan veya yönetimine göre olan." },
{ eski: "Ferağ", yeni: "Uzak durma." },
{ eski: "Feraiz-i iman", yeni: "İmanın şartları." },
{ eski: "Ferda", yeni: "Yarın, gelecek zaman." },
{ eski: "Ferid", yeni: "Eşsiz." },
{ eski: "Ferîk", yeni: "Osmanlı Devleti'nin son dönemi ve Cumhuriyet'in ilk yıllarında kullanılan mirliva ile ferîk-i evvel rütbeleri arasında olan ve günümüz korgeneral rütbesine eşit askerî rütbe." },
{ eski: "Fersude", yeni: "Eskimiş." },
{ eski: "Ferş-i rahıd", yeni: "Yolun yaygısı." },
{ eski: "Feryad", yeni: "Bağırmak, çığlık atmak." },
{ eski: "Fes", yeni: "Sarık." },
{ eski: "Fesad", yeni: "Bozulma." },
{ eski: "Fetret", yeni: "İki olay arasında geçen süre." },
{ eski: "Fetva", yeni: "Din adamının verdiği dini görüş." },
{ eski: "Feve fevc", yeni: "Dalga dalga." },
{ eski: "Fevk", yeni: "Üst." },
{ eski: "Fevkinden", yeni: "Üstünden." },
{ eski: "Feyfa", yeni: "Çöl." },
{ eski: "Feylesof", yeni: "Filozof." },
{ eski: "Feyyal", yeni: "Fil çobanı; file bakan kimse." },
{ eski: "Feyyaz", yeni: "Cömert, eli açık, bol veren veya bereketli." },
{ eski: "Feyz", yeni: "Bağış ve lütufkârlık; fazla suyun yatağından taşması, bir haberin şâyi olması, bir sırrın ifşa edilmesi." },
{ eski: "Feyza", yeni: "Bolluk, bereket, verimlilik." },
{ eski: "Feza", yeni: "Uzay." },
{ eski: "Fezail", yeni: "Faziletler." },
{ eski: "Fıkka", yeni: "Ufak, çok küçük." },
{ eski: "Fırka", yeni: "Siyasal parti veya ayırmak." },
{ eski: "Fıtrat", yeni: "Yaratılış." },
{ eski: "Figan", yeni: "Bağırmak." },
{ eski: "Fikr", yeni: "Düşünce." },
{ eski: "Fikri hürriyet", yeni: "Hürriyet düşüncesi." },
{ eski: "Fikr-i kavmiyet", yeni: "Irkçılık düşüncesi." },
{ eski: "Fikr-i nezih", yeni: "Temiz düşünce." },
{ eski: "Fil hakika", yeni: "Doğrusu, gerçekten." },
{ eski: "Fitne", yeni: "Kargaşa, karışıklık." },
{ eski: "Fuad", yeni: "Kalp, gönül." },
{ eski: "Fuhuş", yeni: "Haddini aşma." },
{ eski: "Fukaha", yeni: "Fıkıh alimleri." },
{ eski: "Furkan-ı hakim", yeni: "Hikmetli Kuran." },
{ eski: "Fünun", yeni: "Fenler." },
{ eski: "Fünun-ı hendese", yeni: "Geometri ilimleri." },
{ eski: "Füshat", yeni: "Genişlik." },
{ eski: "Füsul", yeni: "Mevsim." },
{ eski: "Fütur", yeni: "Bezginlik." },
{ eski: "Füyuzun", yeni: "Feyizler." }
{ eski: "Gafil", yeni: "Aymaz, habersiz, hazırlıksız." },
{ eski: "Gâhi", yeni: "Ara sıra, zaman zaman." },
{ eski: "Gaib", yeni: "Görülmeyen âlem, göz önünde bulunmayan." },
{ eski: "Galebe", yeni: "Yenmek, üstünlük." },
{ eski: "Galeyan", yeni: "Kaynamış, mecazen coşma, hiddetlenme." },
{ eski: "Galeyh", yeni: "Kaynama." },
{ eski: "Galin", yeni: "Yatak." },
{ eski: "Gamgin", yeni: "Oyun." },
{ eski: "Garâbet", yeni: "Gariplikler, tuhaflıklar." },
{ eski: "Garb", yeni: "Batı, Avrupa." },
{ eski: "Gârib", yeni: "Yurdundan uzak kalan, bilinmeyen, müphem, kapalı olan, eşi benzeri olmayan, tek ve nadir, yalnız, kimsesiz, zavallı." },
{ eski: "Gaye", yeni: "Amaç, sonuç, bir şeyin son noktası, uç." },
{ eski: "Gayet", yeni: "Aşırı ölçüde, pek çok." },
{ eski: "Gazel", yeni: "Divan edebiyatının en yaygın nazım şekli." },
{ eski: "Gılzet", yeni: "Kabalık, sertlik." },
{ eski: "Girdab", yeni: "Tehlikeli yer ya da durum." },
{ eski: "Girizan", yeni: "Kaçan, firar eden." },
{ eski: "Girudâr", yeni: "Savaş." },
{ eski: "Girye", yeni: "Gözyaşı." },
{ eski: "Gisu", yeni: "Uzun saç, omuza dökülen saç." },
{ eski: "Gubar", yeni: "Keder." },
{ eski: "Gulgule-hiz", yeni: "Gürültü yapan." },
{ eski: "Gulgules", yeni: "Gürültü, patırtı." },
{ eski: "Gum-nam", yeni: "Eseri kalmamış, kaybolmuş." },
{ eski: "Gunagun", yeni: "Çok çeşitli." },
{ eski: "Gurebâ", yeni: "Yabancı, kimsesiz." },
{ eski: "Gurüb", yeni: "Güneşin batması." },
{ eski: "Gusn", yeni: "Kırılmış dal, ağaç dalı." },
{ eski: "Gümrah", yeni: "Gür, bol, sık, çok." },
{ eski: "Güne", yeni: "Gidiş." },
{ eski: "Güş", yeni: "İşitmek, duymak." },
{ eski: "Güyâ", yeni: "Sanırsın ki, sanki, sözde." },
{ eski: "Güzin", yeni: "Nadide, seçilmiş, seçkin, beğenilmiş." }

{ eski: "Hab gâh", yeni: "Yatak odası." },
{ eski: "Hab-ı sükûn", yeni: "Sakin uyku." },
{ eski: "Habe", yeni: "Sahip olmak." },
{ eski: "Hacet", yeni: "Gereklilik." },
{ eski: "Hacil", yeni: "Utanmak, utanmış." },
{ eski: "Haç", yeni: "Hristiyanlıkta önemli bir sembol." },
{ eski: "Had", yeni: "Yetki, sınır." },
{ eski: "Hadim", yeni: "Hizmetkâr, hizmetçi." },
{ eski: "Haiz", yeni: "Bir şeyi elinde bulunduran, bir şeyi olan." },
{ eski: "Hâk", yeni: "Yer, toprak." },
{ eski: "Hakaik", yeni: "Hakikatler." },
{ eski: "Hakdan", yeni: "Allah’ın yarattığı kul." },
{ eski: "Haki", yeni: "Toprak." },
{ eski: "Hakikat", yeni: "Gerçek." },
{ eski: "Hakikat-ı yelda", yeni: "Uzun gecenin gerçeği." },
{ eski: "Hâkim-i fıtrat", yeni: "Yaratılışın hâkimi." },
{ eski: "Hakir", yeni: "Küçük, önemsiz." },
{ eski: "Hakkı hayat", yeni: "Hayat hakkı." },
{ eski: "Hak-sar", yeni: "Yere sermek, toz toprak içinde kalmış, perişan." },
{ eski: "Hal", yeni: "Durum, vaziyet, görünüş, tavır." },
{ eski: "Halas", yeni: "Kurtuluş, kurtulma." },
{ eski: "Halef", yeni: "Arkadan gelen, ardından gelen kimse." },
{ eski: "Haleti rühiyye", yeni: "Ruh durumu." },
{ eski: "Halife", yeni: "Hz Muhammet’ten sonra, onun vekili olarak Müslümanların imamlığını ve şeriatın koruyuculuğunu yapmakla görevli kimse." },
{ eski: "Halik", yeni: "Yaratıcı, yaratan." },
{ eski: "Halil", yeni: "Dolu, sağanak." },
{ eski: "Halisane", yeni: "Candan." },
{ eski: "Halk", yeni: "Ortaya koymak, meydana çıkarmak." },
{ eski: "Hallak", yeni: "Yaratıcı." },
{ eski: "Hamakat", yeni: "Ahmaklık, aptallık." },
{ eski: "Hamaset", yeni: "Kahraman, kahramanlık, yiğitlik." },
{ eski: "Hamiyyet", yeni: "Milleti himaye etmekte, korumakta, işaretini savunmakta, tembellik etmeyip bütün kuvveti gayret etmek." },
{ eski: "Hamuş", yeni: "Sakin, suskun." },
{ eski: "Han ü man", yeni: "Ev bark, aile ocağı." },
{ eski: "Hande-i nur", yeni: "Parlak gülüş." },
{ eski: "Hane", yeni: "Ev, konut." },
{ eski: "Hanumansız", yeni: "Evsiz." },
{ eski: "Har", yeni: "Hor, hakir, adi, aşağı." },
{ eski: "Hara", yeni: "Tepinme, oynama." },
{ eski: "Harab", yeni: "Yıkılmaya yüz tutmuş ve çok eski, perişan." },
{ eski: "Harameyn", yeni: "Mekke ve Medine şehirlerini birlikte ifade eden tabir." },
{ eski: "Haras", yeni: "Dilsizlik, dilsiz olma." },
{ eski: "Harb", yeni: "Savaş." },
{ eski: "Harde", yeni: "Zorlu." },
{ eski: "Harem", yeni: "Padişahın aile yaşamını sürdürdüğü, padişah, şehzade ve devlet ileri gelenlerine cariye ve eş temin edilen yer." },
{ eski: "Harim-i din", yeni: "Dinin korunması." },
{ eski: "Hârim", yeni: "Yasaklanan, korunan, saygı duyulan şey." },
{ eski: "Harim-i canan", yeni: "Sevgili yuvası." },
{ eski: "Hasbi", yeni: "Gönüllü olarak ve karşılık beklemeksizin yapılan, nedeni olmayan, nedensiz, karşılıksız." },
{ eski: "Hasıl", yeni: "Ortaya çıkan, türeyen, var olan." },
{ eski: "Hasire", yeni: "Zarara uğrayan." },
{ eski: "Hasis", yeni: "Cimri." },
{ eski: "Hasm", yeni: "En büyük düşman." },
{ eski: "Hasmım", yeni: "Düşman." },
{ eski: "Haş", yeni: "Özel, çok yakın." },
{ eski: "Haşa", yeni: "İslam dininde uygun olarak kabul edilmeyen her bir söze ve davranışa sinme." },
{ eski: "Haşr", yeni: "Birlikte olmak, yan yana olma, toplanmak." },
{ eski: "Haşyet", yeni: "Korku, korkma, endişe duyma." },
{ eski: "Hatır", yeni: "Düğün." },
{ eski: "Hatırat-ı latif", yeni: "Tatlı hatıralar." },
{ eski: "Hatip", yeni: "Söz söyleyen, cemaatte topluluğa karşı güzel söz söyleyen." },
{ eski: "Hatmi enfas", yeni: "Nefesleri tükenmek, ölmek." },
{ eski: "Hatve", yeni: "Adım, mesafe." },
{ eski: "Havali", yeni: "Çevre, dolay, yöre." },
{ eski: "Havas", yeni: "Yüksek seviyede olanlar." },
{ eski: "Havatır", yeni: "Akla gelmek." },
{ eski: "Havi", yeni: "İhtiva eden, içeren." },
{ eski: "Havsala", yeni: "Zihnin bir şeyi kavrama derecesi." },
{ eski: "Havvas", yeni: "Yüksek seviyede olanların, üstekilerin." },
{ eski: "Haya", yeni: "Utanmak, çekinmek." },
{ eski: "Hayat-ı nev", yeni: "Yepyeni yaşam." },
{ eski: "Haybet", yeni: "Saygıya dayanan korku, mahremiyet." },
{ eski: "Hayfa", yeni: "Yazık." },
{ eski: "Hayme", yeni: "Çadır." },
{ eski: "Hayret", yeni: "Beklenmedik, şaşırtıcı, garip bir şeyin açtığı şaşkınlık." },
{ eski: "Haysiyet", yeni: "Şeref, itibar." },
{ eski: "Hayyiz", yeni: "Mekân, yer, makam." },
{ eski: "Hazin", yeni: "İçe dokunan, üzüntü verici, acıklı." },
{ eski: "Heder", yeni: "Boşa gitme, ziyan olma; bir işe yaramama, karşılığını alamama, vücudun bir organında görülen uyuşma." },
{ eski: "Helak", yeni: "Ortadan kaldırma, yok etme." },
{ eski: "Helecan", yeni: "Titretme, çarpıntı." },
{ eski: "Hemal", yeni: "Taşımak." },
{ eski: "Hemşizade", yeni: "Kız kardeşin çocuğu." },
{ eski: "Hercümerc", yeni: "Darma dağın." },
{ eski: "Herdem", yeni: "Taşımak." },
{ eski: "Herze", yeni: "Saçma sapan söz ya da davranış, boş laf, söz, lakırdı." },
{ eski: "Hesti", yeni: "Varlık, var olma." },
{ eski: "Heval", yeni: "Dost." },
{ eski: "Hey’et", yeni: "Kurul." },
{ eski: "Heybet", yeni: "Yücelik, azamet, büyüklük." },
{ eski: "Heybetli", yeni: "Görünüşü korku ve saygı uyandıran." },
{ eski: "Heyhat", yeni: "Yazık, yazık ki anlamında kullanılır." },
{ eski: "Heyula", yeni: "Korkunç hayal, ürkütücü şey." },
{ eski: "Hezel", yeni: "Alay, şaka." },
{ eski: "Hezeyan", yeni: "Abuk sabuk konuşma, saçma sapan sözler etme, saçmalama." },
{ eski: "Hezeyas", yeni: "Sayıklama." },
{ eski: "Hezimet", yeni: "Bozgun." },
{ eski: "Hicran-ı müebbed", yeni: "Sonsuz ayrılık." },
{ eski: "Hicran", yeni: "Ayrılık." },
{ eski: "Hidayet", yeni: "Bir kimseyi tanrı tarafından gönderildiğine inanılan doğru yol." },
{ eski: "Hiddet", yeni: "Sinir, öfke." },
{ eski: "Hikmet-i kuran", yeni: "Kurana mahsus hikmet." },
{ eski: "Hilaf", yeni: "Zıt." },
{ eski: "Hilkat", yeni: "Allah’ın yaratması." },
{ eski: "Himmet", yeni: "Kayırma, yardım, çaba, çalışma." },
{ eski: "Hiram", yeni: "Yürüme, gezinme, salınarak eda ve naz ile yürüme." },
{ eski: "Hissi-i milliyet", yeni: "Milliyet duygusu." },
{ eski: "Hizb", yeni: "Kısım, parça." },
{ eski: "Hotoz", yeni: "Eski zamanlarda kadınların başlarına giydikleri süslü serpuş." },
{ eski: "Hödük", yeni: "Anlayışı kıt, kaba saba kimse." },
{ eski: "Hucüm", yeni: "Saldırı." },
{ eski: "Hucüs", yeni: "Sessiz, sakin durmak, alçak gönüllü olmak." },
{ eski: "Huda", yeni: "Doğru yol veya doğru yolu gösteren kişi." },
{ eski: "Hufre", yeni: "Çukur." },
{ eski: "Hulul", yeni: "Bir şeyi çözmek, bir yere intikal etmek, konup yerleşmek." },
{ eski: "Hunu", yeni: "Kanı." },
{ eski: "Hurab", yeni: "Bakımsız kalmış, bakımsızlıktan yıkılacak duruma gelmiş olan." },
{ eski: "Huraf", yeni: "Harfler." },
{ eski: "Hurafat", yeni: "Hurafeler, harfler." },
{ eski: "Hurafe", yeni: "Akla aykırı, uydurma şeyler." },
{ eski: "Huruş aver", yeni: "Gürültü, aşama." },
{ eski: "Huruş", yeni: "Coşku, coşmak." },
{ eski: "Huruşan", yeni: "Esip coşmak." },
{ eski: "Hurüş", yeni: "Kendinden geçme." },
{ eski: "Hutbe", yeni: "Söz söylemek, hitap etmek, konuşmak." },
{ eski: "Hutur", yeni: "Kafası karışmış." },
{ eski: "Hutür", yeni: "Akla getirmek." },
{ eski: "Hüccet", yeni: "Delil, senet." },
{ eski: "Hüdud", yeni: "Sınır." },
{ eski: "Hüfeyre", yeni: "Çukur." },
{ eski: "Hülasa", yeni: "Özet." },
{ eski: "Hülya", yeni: "Tatlı düş, hayal." },
{ eski: "Hümüs", yeni: "Bitkilerin çürümesiyle oluşmuş koyu renkte organik toprak." },
{ eski: "Hün-i mazlum", yeni: "Mazlum kanı." },
{ eski: "Hün", yeni: "Kan." },
{ eski: "Hüruşa", yeni: "Coşup ağlamak." },
{ eski: "Hürüş", yeni: "Coşkun, coşma." },
{ eski: "Hüsn", yeni: "Güzellik." },
{ eski: "Hüsran", yeni: "Mahrumiyet, kayıp, ümitsizlik, elem." },
{ eski: "Hüsran", yeni: "Umulan, beklenilen bir şeyin elde edilememesinden duyulan acı, düş kırıklığı." },
{ eski: "Hüveyde", yeni: "Aşikar." },
{ eski: "Hüzme", yeni: "Demet." }
{ eski: "Irgat", yeni: "Çalışan, işçi." },
{ eski: "Irşâd", yeni: "Doğru yolu göstermek." },
{ eski: "Islah", yeni: "Düzeltme." },
{ eski: "İ’la", yeni: "Yüceltme." },
{ eski: "İ’laya", yeni: "Yüceltmek." },
{ eski: "İane", yeni: "Yardım." },
{ eski: "İbahiyye", yeni: "Haram, yasak olan şeyleri helal kılmış." },
{ eski: "İbn-i avf", yeni: "Abdurrahman b. Avf." },
{ eski: "İbraz", yeni: "Ortaya koymak." },
{ eski: "İbret", yeni: "Kötü, yanlış davranışlardan sakınmayı sağlayan olgu." },
{ eski: "İcazet", yeni: "1. İzin, onay, onaylama. 2. Diploma." },
{ eski: "İcbar", yeni: "Zorlama." },
{ eski: "İctihad", yeni: "Sosyal hayatta şeriatın kaynaklarında yer alamayan soruları çözmek için zihinsel çaba harcama." },
{ eski: "İçtimai", yeni: "Toplumsal." },
{ eski: "İddiay-ı kavmiyet", yeni: "Irkçılık iddiası." },
{ eski: "İdlal", yeni: "Saptırmak." },
{ eski: "İdrak", yeni: "Zihin." },
{ eski: "İffet", yeni: "Namus." },
{ eski: "İfsad", yeni: "Bozgunculuk." },
{ eski: "İgze", yeni: "İzin, onay." },
{ eski: "İhkak", yeni: "Hak." },
{ eski: "İhsan", yeni: "İyilik." },
{ eski: "İhtar", yeni: "Uyarı." },
{ eski: "İhtiram", yeni: "Saygı." },
{ eski: "İhvan", yeni: "1. Yakın dostlar, yakın arkadaşlar. 2. Aynı tarikattan olan kimseler." },
{ eski: "İhya", yeni: "Diriltme." },
{ eski: "İkbal", yeni: "Yüksek bir makama erişme." },
{ eski: "İkdam", yeni: "Gayretle çalışma." },
{ eski: "İkmal", yeni: "Bütünleme." },
{ eski: "İkrar", yeni: "Bildirme, açıkça söylemek." },
{ eski: "İktiham", yeni: "Bir zorluğu giderme." },
{ eski: "İlahi", yeni: "Tanrısal." },
{ eski: "İlhad", yeni: "Küfür, inkar, dinsizlik." },
{ eski: "İlik", yeni: "Kemiklerin iç boşluklarını dolduran doku." },
{ eski: "İlim", yeni: "Evrenin veya olayların bir bölümünü konu olarak seçen, gerçeğe dayanan yöntemlerle sonuç çıkarmaya yarayan düzenli bilgi." },
{ eski: "İllet", yeni: "Hastalık." },
{ eski: "İltia", yeni: "Sığınma." },
{ eski: "İltikaf", yeni: "Kendini bir konuya verme." },
{ eski: "İltiva", yeni: "Kıvrılmak." },
{ eski: "İmdat", yeni: "Yardım." },
{ eski: "İmhal", yeni: "Bırakmak, mühlet verme." },
{ eski: "İmti dad-ı mehibince", yeni: "Heybetli, uzama." },
{ eski: "İmtidat", yeni: "Uzanmak." },
{ eski: "İmtizac", yeni: "Uygunluk." },
{ eski: "İnayet", yeni: "Lütuf, ihsan, iyilik, yardım." },
{ eski: "İncizab", yeni: "Kapılmak." },
{ eski: "İnfan", yeni: "Bilmek." },
{ eski: "İnfial", yeni: "Gücenme, darılma." },
{ eski: "İnfial", yeni: "Tutuşan." },
{ eski: "İnfilali", yeni: "Kızgınlık duyma." },
{ eski: "İnkılap", yeni: "Devrim, değişim." },
{ eski: "İnkıyad", yeni: "Boyun eğme, uyma." },
{ eski: "İnkisar", yeni: "Kırılma, gücenme." },
{ eski: "İnkişaf", yeni: "Gelişim, gelişme." },
{ eski: "İnkişaf", yeni: "Gelişme, gelişim, gelişmiş." },
{ eski: "İnlem", yeni: "Acı sesler." },
{ eski: "İnsaf", yeni: "Acıma, mantığa dayalı adalet duygusu." },
{ eski: "İnsaniyet", yeni: "İnsanlık." },
{ eski: "İnşad", yeni: "Şiir okuma." },
{ eski: "İntibah", yeni: "1. Sinirlerin uyanması, uzuvların harekete geçmesi. 2. Uyanış, uyanma." },
{ eski: "İptidai", yeni: "İlkel mektep, Osmanlı zamanında küçükten büyüğe eğitim düzeyi." },
{ eski: "İrfan", yeni: "Anlama, kültür." },
{ eski: "İrşad", yeni: "Doğru yolu gösteren." },
{ eski: "İsabat", yeni: "Bir şeyi açıklığa kavuşturmak, delil getirmek." },
{ eski: "İskandil", yeni: "Derinlik ölçme aleti." },
{ eski: "İskirham", yeni: "Yalvarış." },
{ eski: "İsti dad", yeni: "Yetenek." },
{ eski: "İstibdat", yeni: "Baskıcı yönetim." },
{ eski: "İstidat", yeni: "Yetenek, hazırlık." },
{ eski: "İstihfaf", yeni: "Hafife alma." },
{ eski: "İstihkar", yeni: "Hakir, zelil." },
{ eski: "İstikbal", yeni: "Gelecek." },
{ eski: "İstiknah", yeni: "Araştırma." },
{ eski: "İstikrah", yeni: "İğrenmek, tiksinmek." },
{ eski: "İstimdat", yeni: "Tehlikeli durumlarda yardım isteme." },
{ eski: "İstinsah", yeni: "Kopye." },
{ eski: "İstirham", yeni: "Yalvarma." },
{ eski: "İşar", yeni: "Göstermek." },
{ eski: "İşrak", yeni: "Parıltı." },
{ eski: "İşve", yeni: "Aldatıcı, çekici, hoş tavır." },
{ eski: "İşve", yeni: "Cilve." },
{ eski: "İtilla", yeni: "Yükselme." },
{ eski: "İttihaz", yeni: "Sayma, tutma." },
{ eski: "İyan", yeni: "Aşikar." },
{ eski: "İyazen", yeni: "Sığınma." },
{ eski: "İyd", yeni: "Bayram." },
{ eski: "İzan", yeni: "Kavrayış." },
{ eski: "İzdiham", yeni: "Kalabalık." },
{ eski: "İzmihlal", yeni: "Çökme, yıkılma, yok oluş." },
{ eski: "İzzet", yeni: "Büyüklük, ululuk, yücelik." }
{ eski: "Jamime", yeni: "Genelleştirme." },
{ eski: "Janafeyri", yeni: "İki yön." },
{ eski: "Jazib", yeni: "Eziyet etme." },
{ eski: "Jemaşare", yeni: "Seyretmek." },
{ eski: "Jemine", yeni: "Güven verme." },
{ eski: "Jerezu", yeni: "Bakışma." },
{ eski: "Jevcih", yeni: "Yönetme." },
{ eski: "Jimsal’i ilahi", yeni: "İlahi benzetme." },
{ eski: "K: arar ı erzeli", yeni: "En rezil karar." },
{ eski: "Ka betullah", yeni: "Allah’ın kabesi." },
{ eski: "Kabail", yeni: "Kabileler." },
{ eski: "Kâbetullah", yeni: "Allah'ın kabesi." },
{ eski: "Kabil", yeni: "Mümkün olan, kabul edilen." },
{ eski: "Kabiliyet", yeni: "Yetenek." },
{ eski: "Kabristan", yeni: "Mezarlık." },
{ eski: "Kabus -i huni", yeni: "Kanlı kabus." },
{ eski: "Kadı asker", yeni: "Osmanlıda şeri davalara bakan askeri hâkim." },
{ eski: "Kadid", yeni: "İskelet." },
{ eski: "Kadim", yeni: "Çok eski zamandan var olmuş veya eskiden beri var olan." },
{ eski: "Kadr", yeni: "Değer bilmek." },
{ eski: "Kadrül lahtan", yeni: "Allah’ ın kaderi." },
{ eski: "Kâfi", yeni: "Yeter." },
{ eski: "Kafile", yeni: "Grup." },
{ eski: "Kaftan", yeni: "İpekli kumaş, giysi." },
{ eski: "Kah olmak", yeni: "Ara sıra, kimi kez." },
{ eski: "Kahbe", yeni: "Hilekâr, kalleş." },
{ eski: "Kair", yeni: "Derinlik, dip." },
{ eski: "Kalpak", yeni: "Deriden, kürkten başlık." },
{ eski: "Kaltaban", yeni: "Hileci, düzenci." },
{ eski: "Kamer", yeni: "Ay." },
{ eski: "Kâmilen", yeni: "Topluca, hep birlikte." },
{ eski: "Kamş", yeni: "Meşelik ağaç." },
{ eski: "Kandil", yeni: "Fener." },
{ eski: "Kani", yeni: "Kişinin düşünerek vardığı ve inandığı sonuç; inanılan düşünce, kesin düşünce." },
{ eski: "Kanun- i sa’y", yeni: "Çalışma kanunu." },
{ eski: "Kanun-i esasi", yeni: "Anayasa." },
{ eski: "Kar ü bâr", yeni: "Vur kaç tekniği." },
{ eski: "Kâr", yeni: "Kazanç." },
{ eski: "Karar-ı erzel", yeni: "En rezil karar." },
{ eski: "Karban", yeni: "Kervan." },
{ eski: "Kari", yeni: "Okuyucu." },
{ eski: "Karib", yeni: "Yakın." },
{ eski: "Karye", yeni: "Köy." },
{ eski: "Kasaid", yeni: "Kasideler." },
{ eski: "Kasvet", yeni: "İç sıkıntı." },
{ eski: "Katre- i avare", yeni: "Başıboş damla." },
{ eski: "Katre", yeni: "Damlacıklar, kuyudan damlayan su." },
{ eski: "Kavi", yeni: "Kuvvetli." },
{ eski: "Kavim", yeni: "Aynı soydan gelen, töre, dil ve kültürleri bir olan insan topluluğu." },
{ eski: "Kavm-i Necib", yeni: "Soylu, seçkin, temiz ulus." },
{ eski: "Kavmiyyet", yeni: "Irkçılık." },
{ eski: "Kavzan", yeni: "Titreyen." },
{ eski: "Kayd", yeni: "Bağlamak." },
{ eski: "Kayd -ı ömür", yeni: "Yaşadığı süreç." },
{ eski: "Kebe", yeni: "Kısa kepenek." },
{ eski: "Keçe", yeni: "Koyun, keçi, deve, tavşan vb. gibi hayvanların yapağısının, tüyünün dürülmesi, dövülmesi yoluyla yapılan kalın kumaş." },
{ eski: "Kehvâne", yeni: "Beşik." },
{ eski: "Kemal- i Acizlik", yeni: "Güçsüzlük." },
{ eski: "Kemal -i Şiddet", yeni: "Büyük bir şiddet." },
{ eski: "Kerhen", yeni: "İğrenerek." },
{ eski: "Keşmekeş", yeni: "Karışık olma durumu." },
{ eski: "Kevni", yeni: "Oluşan, ait ve müteallik." },
{ eski: "Kevr", yeni: "Devretmek, dönmek." },
{ eski: "Kevre", yeni: "Zayıf, çelimsiz." },
{ eski: "Kılağı", yeni: "Taş üzerinde bilinen bir kesici aracın keskin yüzüne yapı zarı ve iyi kesilebilmesi için gereken çok ince çelik parçalar." },
{ eski: "Kıyam", yeni: "Ayağa kalkış, bir şeye girişme, kalkışma." },
{ eski: "Kıyam edip", yeni: "Ayağa kalkmak." },
{ eski: "Kıyamı Haşr", yeni: "Kıyamet günü." },
{ eski: "Kibar ı ümmeti", yeni: "Ümmetin büyüğü." },
{ eski: "Kibari", yeni: "Büyükler." },
{ eski: "Kitabü’l fetva", yeni: "Fetva kitabı." },
{ eski: "Koğ", yeni: "Çekiştirme, kötüleme." },
{ eski: "Kontrant", yeni: "Sözleşme." },
{ eski: "Kopuk", yeni: "Toplum kurallarına uymayan, işsiz güçsüz." },
{ eski: "Kudumiye", yeni: "Büyük bir kimseye yoldan geldiği zaman sunulan hediye." },
{ eski: "Kurb", yeni: "Yakın." },
{ eski: "Kûrs-î celâl", yeni: "Hiddet kürsüsü." },
{ eski: "Kuruntu", yeni: "Yanlış sanı, düşünce." },
{ eski: "Kuvai", yeni: "Kuvvetler, güçler." },
{ eski: "Kuyûd", yeni: "Kayıtlar, sınırlamalar." },
{ eski: "Kübra", yeni: "En büyük olan yol ya da büyük." },
{ eski: "Küdein", yeni: "İlaç." },
{ eski: "Küfar", yeni: "Kâfirler." },
{ eski: "Kühen", yeni: "Köhne." },
{ eski: "Kühne", yeni: "Gözü pek." },
{ eski: "Kühsar", yeni: "Dağlık yer, dağ tepesi." },
{ eski: "Külhan", yeni: "Kabadayı, serseri." },
{ eski: "Külhanbeyi", yeni: "Kabadayı, serseri." },
{ eski: "Kürs-i mehib", yeni: "Heybetli kürsü." },
{ eski: "Kürsi", yeni: "Taht, hükümdarlık." }
{ eski: "La yüsel", yeni: "Sorumsuz" },
{ eski: "Lafz", yeni: "Ağızdan çıkan anlamlı ses veya sözün bildirilmesi" },
{ eski: "Lafz-ı muhkem", yeni: "Başka bir ihtimal taşımayan açık manalı ayet ve hadislerle fıkıh usulünde açıklık bakımından en üst düzeydeki lafız için kullanılan bir terim" },
{ eski: "Lahavle", yeni: "Artık sabrın tükendiğinde belirtmek için kullanılır." },
{ eski: "Lahik", yeni: "Ulaşan" },
{ eski: "Lahut", yeni: "ruhani, insanın ilahi ve manevi yönü" },
{ eski: "Lahut", yeni: "İlahi alem, manevi alem" },
{ eski: "Lahuti", yeni: "Tanrısal" },
{ eski: "Lahza", yeni: "An" },
{ eski: "Lakin", yeni: "Ama, ancak, fakat" },
{ eski: "Lal", yeni: "Dilsiz" },
{ eski: "Lamise", yeni: "Dokunma" },
{ eski: "Lane", yeni: "Yuva, ev" },
{ eski: "Laşe", yeni: "Leş" },
{ eski: "Latif", yeni: "Güzel" },
{ eski: "Latif", yeni: "Nazik ve merhametli davranmak, iyi muamele etmek" },
{ eski: "Leb", yeni: "Dudak" },
{ eski: "Leb-i derya", yeni: "Denizin altı" },
{ eski: "Lebriz", yeni: "Taşkın, taşacak kadar, ağzına kadar dolu" },
{ eski: "Lebriz-i meserret", yeni: "Sevinçle dolmak" },
{ eski: "Ledün", yeni: "Zaman ve mekân zarfı" },
{ eski: "Leim", yeni: "yol göstermek" },
{ eski: "Leim", yeni: "Alçak" },
{ eski: "Lem’a lem’a", yeni: "Parıl parıl" },
{ eski: "Lemeân", yeni: "Parlama, parıldama" },
{ eski: "Lems", yeni: "Dokunmak" },
{ eski: "Lerzan eyle-", yeni: "Titremek" },
{ eski: "Lerzedar", yeni: "Titrek, titreyen" },
{ eski: "Levazım", yeni: "Lazım olan şeyler, askeri malzemeler" },
{ eski: "Levh-i güzin", yeni: "Seçkin tablo" },
{ eski: "Leyâl", yeni: "Geceler, karanlık" },
{ eski: "Leyl-gun", yeni: "Gece renkli" },
{ eski: "Leyl-i matem", yeni: "Matem gecesi" },
{ eski: "Leyse li’l insani illa mâ-se-â", yeni: "İnsanın kendi çaba ve çalışmasından başka bir şey yoktur." },
{ eski: "Lihye-i Paki", yeni: "Hz. Peygamberin yaratılışını, dış görünüşünü, mübarek vücut şeklini ve onun bütün güzel sıfatlarını ifade etmek için kullanılan bir deyim" },
{ eski: "Lika", yeni: "Kavuşma" },
{ eski: "Lisan", yeni: "Dil" },
{ eski: "Lisan-ı gayb", yeni: "Görünmeyen alemin dili" },
{ eski: "Lisan-ı hal", yeni: "Hal dili" },
{ eski: "Lisan-ı şiir", yeni: "Şiir dili" },
{ eski: "Lüb", yeni: "Öz" }
{ eski: "Ma budanlar", yeni: "ilah" },
{ eski: "Ma sum", yeni: "suçsuz" },
{ eski: "Ma’bed", yeni: "tapınak, ibadet yeri" },
{ eski: "Ma’bed-i feyyaz", yeni: "bereket veren" },
{ eski: "Ma’mafih", yeni: "durum böyleyken" },
{ eski: "Ma’na", yeni: "anlam" },
{ eski: "Ma’sume", yeni: "günahsız millet" },
{ eski: "Maarifet", yeni: "herkesin gösteremeyeceği beceri, beceriklilik, hüner, ustalık" },
{ eski: "Mademki", yeni: "çünkü" },
{ eski: "Mağribi aksaya", yeni: "en uzak batı" },
{ eski: "Mahal", yeni: "yer, yöre" },
{ eski: "Mahfil", yeni: "toplandirilacak yer" },
{ eski: "Mahirane", yeni: "ustaca" },
{ eski: "Mahiyet", yeni: "Nitelik, önem" },
{ eski: "Mahiyyet", yeni: "bir şeyin iç yüzü, aslı, esası" },
{ eski: "Mahkûm", yeni: "Esir" },
{ eski: "Mahlûkat", yeni: "Yaratık" },
{ eski: "Mahmur", yeni: "sarhoşluğun verdiği uyuşukluk, sersemlik" },
{ eski: "Mahrum", yeni: "yoksun" },
{ eski: "Mahviyyet", yeni: "Alçak gönüllülük" },
{ eski: "Mahz", yeni: "Sade" },
{ eski: "Maişet", yeni: "Geçinme" },
{ eski: "Makber", yeni: "Mezar" },
{ eski: "Makrun", yeni: "Ulaşılmış, kavuşulmuş olan" },
{ eski: "Maksad", yeni: "amaç" },
{ eski: "Malik", yeni: "Sahip" },
{ eski: "Malike l mülk", yeni: "mülkün sahibi" },
{ eski: "Malta", yeni: "Güney Avrupa’dan Orta Akdeniz’de yer alan Sicilya’nın güneyindeki adalar devleti" },
{ eski: "Mamelek", yeni: "Bir kimsenin para ile ölçülebilen her türlü mal, hak ve borçların tümü" },
{ eski: "Mani", yeni: "Engel" },
{ eski: "Manzur", yeni: "Görülen, bakılan, nazar edilen" },
{ eski: "Masivar", yeni: "Allah’ın dışındaki varlıklar" },
{ eski: "Maskara", yeni: "Eğlendirici" },
{ eski: "Masnu", yeni: "sanat eseri" },
{ eski: "Matbaa", yeni: "Basma evi" },
{ eski: "Matbuat", yeni: "Basın" },
{ eski: "Matem", yeni: "Yas" },
{ eski: "Matlub", yeni: "İstenilen" },
{ eski: "Matvi", yeni: "Bükülü, dürülmüş şey" },
{ eski: "Maun", yeni: "Yardım ve zekât, Eve lâzım şeyler. Ev eşyası." },
{ eski: "Mazi", yeni: "geçmiş" },
{ eski: "Mazik", yeni: "Dar yer" },
{ eski: "Mazlum", yeni: "Zulüm görmüş" },
{ eski: "Mazlümine", yeni: "Mazlumlar" },
{ eski: "Me mül", yeni: "Umulan, beklenen" },
{ eski: "Me var", yeni: "Sekiz cennetten üçüncü" },
{ eski: "Me yüs", yeni: "Ümitsiz, üzgün" },
{ eski: "Me’lun", yeni: "Lanetli" },
{ eski: "Meal i hilkute", yeni: "Yaratılış manası" },
{ eski: "Meal", yeni: "Anlam" },
{ eski: "Medfenin", yeni: "Ölüm" },
{ eski: "Medfun", yeni: "Defnedilmiş" },
{ eski: "Medhuş", yeni: "Dehşete uğramış" },
{ eski: "Mefahir", yeni: "Övünme, övünülecek şeyler" },
{ eski: "Mefkure", yeni: "Gaye, ülkü, ideal" },
{ eski: "Mehib", yeni: "Heybetli" },
{ eski: "Mekabir", yeni: "Kabirler, mezarlar, mezarlıklar" },
{ eski: "Mektep", yeni: "Okul" },
{ eski: "Mel anetleri", yeni: "Melunluk" },
{ eski: "Mel un", yeni: "Kötü, alçak, yaramaz" },
{ eski: "Melahat", yeni: "Güzel" },
{ eski: "Melal", yeni: "Can sıkıntısı, usanma, kader" },
{ eski: "Melkandler", yeni: "Mezarlar" },
{ eski: "Memdud", yeni: "Uzatılmış, yayılmış, çekilmiş" },
{ eski: "Menar", yeni: "Aydın, kültürlü, görgülü, ileri görüşlü" },
{ eski: "Menazır", yeni: "Görünüş" },
{ eski: "Menba", yeni: "Kaynak, pınar" },
{ eski: "Menevir", yeni: "Bir şey üzerinde dalgalanıyormuş hissini veren parlak renkler meydana gelmesi" },
{ eski: "Menzil i aram", yeni: "Dinlenme yeri" },
{ eski: "Menzil-i Feyza", yeni: "İlim dolu nehir" },
{ eski: "Mer", yeni: "Elli" },
{ eski: "Merared", yeni: "Acılık" },
{ eski: "Merartib", yeni: "dereceler" },
{ eski: "Merayan", yeni: "engebeli" },
{ eski: "Merbüd", yeni: "Bağlı" },
{ eski: "Merdane", yeni: "Yiğitçe" },
{ eski: "Merdüd", yeni: "Geri çevrilmiş" },
{ eski: "Merdüm", yeni: "İnsan" },
{ eski: "Mersiye", yeni: "Divan edebiyatında ölüm konusunu işleyen şiir" },
{ eski: "Mes’uliyet", yeni: "Sorumluluk" },
{ eski: "Mesacidin", yeni: "Secde edenler" },
{ eski: "Mesire", yeni: "Gezilecek yer" },
{ eski: "Mestur", yeni: "Örtülmüş, setredilmiş, gizlenmiş" },
{ eski: "Meş al i vahdet", yeni: "Birlik meşalesi" },
{ eski: "Meş’üm", yeni: "Uğursuz, kir, pis, bedbaht" },
{ eski: "Meşhed", yeni: "Mezar, şehitlik" },
{ eski: "Meşhudat", yeni: "Tanıklık" },
{ eski: "Meşhüd", yeni: "Gözlemlenen, görülen" },
{ eski: "Meşiyih", yeni: "Önderler, liderler" },
{ eski: "Meşiyyet", yeni: "İrade, istek, yürüyüş, yürütme" },
{ eski: "Meşreb", yeni: "Yaratılış" },
{ eski: "Meta-ı mebzul", yeni: "Bolca bulunan ucuz nesne" },
{ eski: "Metalib", yeni: "İstenen şeyler" },
{ eski: "Methal", yeni: "Giriş" },
{ eski: "Mev üd i", yeni: "Varlık ve yokluk" },
{ eski: "Mevc i tufan", yeni: "Hak yoldan sapkınlık" },
{ eski: "Mevcan mevc", yeni: "Dalga dalga" },
{ eski: "Mevce", yeni: "Dalga" },
{ eski: "Mevcfidat", yeni: "Ölüm" },
{ eski: "Mevcud", yeni: "Var olan, varlık" },
{ eski: "Mevhum", yeni: "Gerçekte olmayıp varsayılan, var diye düşünülen" },
{ eski: "Mevki", yeni: "Yer" },
{ eski: "Mevkib", yeni: "Kafile, alay, kortej" },
{ eski: "Mevkid-i şad", yeni: "Sevinç alayı" },
{ eski: "Mevküt", yeni: "Vakitli" },
{ eski: "Mevşuk", yeni: "Güvenilir" },
{ eski: "Mevzu", yeni: "Konu" },
{ eski: "Meyil", yeni: "Eğilme" },
{ eski: "Meyse", yeni: "Yürümek" },
{ eski: "Meyus", yeni: "Ümitsiz, üzgün" },
{ eski: "Meyüsane", yeni: "Ümitsizce" },
{ eski: "Meyyit", yeni: "Ölü" },
{ eski: "Mezbele", yeni: "Çöplük" },
{ eski: "Mezellet", yeni: "Alçaklık, düşkünlük" },
{ eski: "Mihnet", yeni: "Üzüntü, sıkıntı" },
{ eski: "Mihrak semavid", yeni: "Odak noktası, merkez" },
{ eski: "Mihrap", yeni: "İmamın camide namaz kıldığı yer" },
{ eski: "Mihriban", yeni: "Sevilen" },
{ eski: "Mikyas", yeni: "Ölçü" },
{ eski: "Millet-i merhume", yeni: "Ölü millet" },
{ eski: "Misyoner", yeni: "Hristiyan olmayan toplumlardan bu dini yaymaya çalışan kimse" },
{ eski: "Mokbor", yeni: "Mezar, gömüt ya da kabir" },
{ eski: "Mu’tandın", yeni: "İstenen şey" },
{ eski: "Muabbededn", yeni: "Sonsuza dek" },
{ eski: "Muaddili", yeni: "Benzer, denk, eşit, eş değer" },
{ eski: "Muammer", yeni: "Uzun ömürlü, uzun yaşayan" },
{ eski: "Muarra", yeni: "Çıplak, temiz, pak, arınmış" },
{ eski: "Muazzam cereyanlar", yeni: "Büyük akış" },
{ eski: "Muazzam", yeni: "Eşsiz, büyük, yüce" },
{ eski: "Muazzezzdi", yeni: "Aziz, yüce, kutsal" },
{ eski: "Mubassır", yeni: "Okullarda öğrencilerin durumu ile ilgilenen ve düzeni sağlamakla görevli kimse" },
{ eski: "Mucahid", yeni: "Cihad eden" },
{ eski: "Mugalyanuzar", yeni: "Güzel kokan çiçek" },
{ eski: "Muğber", yeni: "Güvenlik" },
{ eski: "Muğber", yeni: "Kırgın, küskün, gücenmiş, darılmış" },
{ eski: "Muhacir", yeni: "Mekke’den Medine’ye göç edenler" },
{ eski: "Muhakkar", yeni: "Hakir görülen, hakarete uğramış" },
{ eski: "Muhal", yeni: "Mümkün olmayan, olamaz, imkânsız, olanaksız" },
{ eski: "Muhalif", yeni: "Aykırı" },
{ eski: "Muhammer Tıynet", yeni: "Yoğrulmuş maya" },
{ eski: "Muharrem", yeni: "Ay takvimin birinci ayı, aşure ayı" },
{ eski: "Muhassıl", yeni: "Husule getiren, hâsıl eden, meydana getiren" },
{ eski: "Muhat", yeni: "Etrafı çevrilmiş. Etrafı kuşatılan. Bir şey içinde bulunan" },
{ eski: "Muhit", yeni: "Çevre" },
{ eski: "Muhit-i ilim", yeni: "İlmi çevre" },
{ eski: "Muhkem", yeni: "Sağlam, sağlamlaştırılmış, kuvvetli" },
{ eski: "Muhtasar", yeni: "Kısa, özet, az" },
{ eski: "Muhtefi", yeni: "Gizlenen, saklı, gizli" },
{ eski: "Muhterem", yeni: "Saygıdeğer, hürmete layık" },
{ eski: "Mukabil", yeni: "Karşılık" },
{ eski: "Mukaddes", yeni: "Her türlü çirkinlik ve eksiklikten arınmış, kutsal" },
{ eski: "Mukallid", yeni: "Taklitçi, başkasına özenerek onun gibi olmaya çalışan" },
{ eski: "Mukarrer", yeni: "Kararlaşmış, kesinlik kazanmış; hakkında şüphe olmayan mesele" },
{ eski: "Mukassı", yeni: "Kasvet veren, sıkıntılı, kasvetli. Sıkıcı, dar" },
{ eski: "Muktadas", yeni: "Örnekler" },
{ eski: "Muktedir", yeni: "İktidar sahibi" },
{ eski: "Munis", yeni: "Alışılmış, ehlileşmiş, cana yakın, sevimli" },
{ eski: "Murad ı evvel", yeni: "Osmanlı padişahı" },
{ eski: "Murad ın", yeni: "Birinci Murad, metin kuvvetli sağlam" },
{ eski: "Murdar", yeni: "Pis, kirli, mülevves, temiz olmayan" },
{ eski: "Musahabe", yeni: "Görüşme, konuşma, söyleşi, sohbet" },
{ eski: "Muhasebede", yeni: "Röportaj" },
{ eski: "Musanlar", yeni: "Sanat" },
{ eski: "Musıki", yeni: "Müzik" },
{ eski: "Musıki-şinas", yeni: "Müzikle uğraşan" },
{ eski: "Musin", yeni: "Yaşlı, ihtiyarlamış" },
{ eski: "Musubet", yeni: "Olumsuz" },
{ eski: "Mutad", yeni: "Alışılmış" },
{ eski: "Mutarna", yeni: "Taravetli, taze" },
{ eski: "Mutassıl", yeni: "Beraber" },
{ eski: "Mutefelsit", yeni: "Filozof kesilmek" },
{ eski: "Muteval-i Leyal", yeni: "Sürekli uzayan" },
{ eski: "Muvaffak", yeni: "Başarılı" },
{ eski: "Muvaffakiyet", yeni: "Başarı, başarmak" },
{ eski: "Muzdim", yeni: "Karanlık, dehşetli" },
{ eski: "Muzi", yeni: "Aydınlık, ışık veren, parlak" },
{ eski: "Muztar", yeni: "Zorlanmış. Cebr olunmuş. Mecbur kalış. Çaresiz kalıp başı sıkılan" },
{ eski: "Mübdiane", yeni: "Zorunlu" },
{ eski: "Mübhem", yeni: "İyice belli olmayan, belirsizlik, gizli" },
{ eski: "Mübin", yeni: "Kötüyle iyiyi ayıran" },
{ eski: "Mücadele", yeni: "Savaş" },
{ eski: "Mücaz", yeni: "Câiz görülmüş, yapılabilir, uygun ve muvafık görülmüş" },
{ eski: "Müctehid", yeni: "İslam hukuk alimi, Âyet ve hadîslerden hüküm çıkaran büyük âlim" },
{ eski: "Müderris", yeni: "Medrese ya da camilerde ders veren âlim, hoca" },
{ eski: "Müdrik", yeni: "Bilge" },
{ eski: "Müebbed", yeni: "Ebedi" },
{ eski: "Müedda", yeni: "Mana, anlam, mefhum, kavram" },
{ eski: "Müemad", yeni: "Sürekli" },
{ eski: "Müessese", yeni: "Kurum" },
{ eski: "Müeyyed", yeni: "Doğrulanmış, sağlam" },
{ eski: "Müfekkire", yeni: "Düşünme gücü ve kuvveti" },
{ eski: "Mühim", yeni: "Önemli" },
{ eski: "Mükendidir", yeni: "Boyun eğen" },
{ eski: "Mülahazanyan", yeni: "Düşünce" },
{ eski: "Mülazım", yeni: "Bir kimseye bağlı gibi olan, maaşsız acemilik hizmeti" },
{ eski: "Mülevves", yeni: "Kirli, pis, bulaşık" },
{ eski: "Mülk", yeni: "Vakıf olmayan, doğrudan doğruya birinin malı olan yer ya da yapı" },
{ eski: "Mültecir", yeni: "Sığınan" },
{ eski: "Müncel", yeni: "Şimdiki versiyon" },
{ eski: "Müncezib", yeni: "Beriye çekilen, cezbedilen. İncizab eden" },
{ eski: "Mündemic", yeni: "Dürülüp sarılan, içine sokulmuş olan" },
{ eski: "Mündeşir", yeni: "Dehşet içinde kalmış plan" },
{ eski: "Münevvim", yeni: "Uyutucu, uyku veren ilaç" },
{ eski: "Münhasır", yeni: "Belli bir sınır içinde olup harice tecavüz etmeyen, inhisar eden, her yanı çevrili" },
{ eski: "Münkesir", yeni: "Kırılmış, kırık" },
{ eski: "Müphem", yeni: "Kapalı, örtülü, belirsiz" },
{ eski: "Mürde", yeni: "Ölmüş kişi, ölü" },
{ eski: "Mürted", yeni: "Müslüman iken dinden çıkan, kâfir olan kimse" },
{ eski: "Müsamere", yeni: "Mekteplerde talebelerin oynadıkları piyes" },
{ eski: "Müsangar", yeni: "Küçük, küçücük" },
{ eski: "Müsarf", yeni: "Saçan, su veren" },
{ eski: "Müslih", yeni: "Islah eden, iyileştiren, terbiye edici" },
{ eski: "Müstagrak", yeni: "Kendini bilmeyecek derecede dalgın olan" },
{ eski: "Müstağrak", yeni: "Gark olmuş, dalmış, batmış" },
{ eski: "Müstahil", yeni: "İmkânsız, olmayacak şey, boş" },
{ eski: "Müstakbel", yeni: "İleri bir tarihte beklenen, gelecekteki" },
{ eski: "Müstakbele", yeni: "gelecek" },
{ eski: "Müstarfil", yeni: "Dil döken" },
{ eski: "Müşeyyed", yeni: "Yüksek ve sağlam, metin yapılı, kuvvetlendirilmiş, sağlamlaştırılmış" },
{ eski: "Müşfik", yeni: "Şefkatle seven, acıyan, merhametli" },
{ eski: "Müşkil", yeni: "Zorluk, güçlük, zor olan iş, çetin
{ eski: "Naagd", yeni: "Para" },
{ eski: "Naaş", yeni: "Ceset" },
{ eski: "Naçar", yeni: "Çaresi olmayan, çaresiz" },
{ eski: "Nadan", yeni: "Bilgisiz, cahil, hödük" },
{ eski: "Naf", yeni: "Göbek, orta" },
{ eski: "Naf-ı asar", yeni: "Faydalı eserler" },
{ eski: "Naga", yeni: "Vakitsiz" },
{ eski: "Na-hak", yeni: "Haksız, beyhude, boş" },
{ eski: "Nakkad", yeni: "Tenkidci, bir şeyin iyisini kötüsünü ayıran" },
{ eski: "Nale", yeni: "İnleyip, sızlamak, inilti, feryat" },
{ eski: "Nale-sera", yeni: "Son akşam" },
{ eski: "Nam", yeni: "İsim, ad, lâkab, ün, şan" },
{ eski: "Na-mahdud", yeni: "Sınırsız, hudutsuz" },
{ eski: "Na-mahrem", yeni: "Mahrem olmayan; kendisi ile evlenilmesi haram olmayan" },
{ eski: "Namdar", yeni: "Ünlü, şöhretli, meşhur" },
{ eski: "Na-mütenahi", yeni: "Sınırsız, sonsuz, engin" },
{ eski: "Namzet", yeni: "Aday" },
{ eski: "Na-peyda", yeni: "Belirsiz" },
{ eski: "Nara", yeni: "Yüksek sesle bağırma, haykırma" },
{ eski: "Nas", yeni: "Halk, insanlar" },
{ eski: "Nasara", yeni: "Hristiyanlar, Nasraniler" },
{ eski: "Nasiye", yeni: "Çehrenin gösterişi, alın, yüz" },
{ eski: "Nasula", yeni: "İnsanın beşeri yönü" },
{ eski: "Nasüt", yeni: "İnsanlık, insanlar ve onlarla alâkalı şeyler" },
{ eski: "Nazar", yeni: "Bakış, görüş, göz değmesi" },
{ eski: "Nazariyat", yeni: "Kitabî bilgiler, görüşler, ispatlanmamış düşünceler" },
{ eski: "Naze", yeni: "Cilveli, nazlı" },
{ eski: "Nazele", yeni: "Yüzsüz" },
{ eski: "Nazenin", yeni: "İnce yapılı, cilveli, edalı" },
{ eski: "Nebat", yeni: "Bitki, Yemen diyarında bir kabile adı" },
{ eski: "Nebi", yeni: "Tanrının buyruklarını ileten, onları aydınlatan kimse, peygamber" },
{ eski: "Nebiyy-i masum", yeni: "Masum kimseler" },
{ eski: "Necat", yeni: "Kurtuluş, selamet" },
{ eski: "Necib", yeni: "Soylu, cömert, kerim kişi" },
{ eski: "Necm", yeni: "Yıldız" },
{ eski: "Nedamet", yeni: "Pişmanlık, nedâmet etmek" },
{ eski: "Nefer", yeni: "Er" },
{ eski: "Nefh", yeni: "Güzel kokunun yayılması, kokmak" },
{ eski: "Nefha", yeni: "Esme, esinti, üfürük" },
{ eski: "Nef-i Şahsi", yeni: "Kişilik" },
{ eski: "Nefrin", yeni: "Lanet, nefret, beddua" },
{ eski: "Nefs", yeni: "Ruh, hayat, asıl; bedenin hissi istekleri" },
{ eski: "Nehar", yeni: "Gündüz" },
{ eski: "Nehy", yeni: "Yasaklama, yasak edilen şey" },
{ eski: "Nekalin", yeni: "İşkence" },
{ eski: "Nekbet", yeni: "Felaket, talihsizlik, şanssızlık, bahtsızlık" },
{ eski: "Nescid", yeni: "Mısralar" },
{ eski: "Nesim", yeni: "Hoş ve hafif rüzgâr" },
{ eski: "Nesim-i safa", yeni: "Açık havadaki ayaz rüzgâr" },
{ eski: "Nesrin", yeni: "Yaban gülü" },
{ eski: "Neşet", yeni: "Meydana gelme, çıkma" },
{ eski: "Neşide", yeni: "Manzume, şiir" },
{ eski: "Neşr", yeni: "Yayma, dağıtma" },
{ eski: "Neva", yeni: "Ahenk, ses, güzel sadâ, nağme, avaz" },
{ eski: "Nev-bahar", yeni: "İlkbahar" },
{ eski: "Nevbet", yeni: "Nöbet, sıra ile görülen iş" },
{ eski: "Nevha", yeni: "Ölüye sesli ağlamak, ağıt" },
{ eski: "Neviye", yeni: "Torun" },
{ eski: "Nevmid", yeni: "Ümidsiz, me'yus, mükedder, cesareti kırılmış" },
{ eski: "Nezir", yeni: "Korkutan, cezayı haber veren" },
{ eski: "Nidâ", yeni: "Ses, seslenme, sesleniş" },
{ eski: "Nifak", yeni: "Müslüman gibi görünüp kâfir olmak, iki yüzlülük" },
{ eski: "Nigah", yeni: "Bakmak, nazar etmek, bakış" },
{ eski: "Nigah-ı ibret", yeni: "İbretli bakış" },
{ eski: "Nigeh-ban", yeni: "Gözcü, bekçi" },
{ eski: "Niha", yeni: "Yas tutmak" },
{ eski: "Nihan", yeni: "Gizli, saklı, bulunmayan, mevcut olmayan" },
{ eski: "Nim", yeni: "Yarım, nısf, buçuk, yarı" },
{ eski: "Nira", yeni: "Cehennem" },
{ eski: "Nisar", yeni: "Saçmak, dağıtmak" },
{ eski: "Nisbetiye", yeni: "Bağlantısı olmak, ilgisi olmak" },
{ eski: "Nişane", yeni: "Alâmet, işaret, iz" },
{ eski: "Nitak", yeni: "Kuşak, kemer" },
{ eski: "Niyaz", yeni: "Dilek, yalvarma, dua" },
{ eski: "Nukus", yeni: "Resimler, nakışlar" },
{ eski: "Numüne", yeni: "Örnek" },
{ eski: "Nur-ı Nazar", yeni: "Bakışın ışığı" },
{ eski: "Nur-ı Uluhiyet", yeni: "İlahi ışık" },
{ eski: "Nur-i Didan", yeni: "Nur yüzlü" },
{ eski: "Nusret", yeni: "Zafer için yardım" },
{ eski: "Nuş", yeni: "Tatlı şerbet gibi içilecek şey" },
{ eski: "Nübüvvet", yeni: "Peygamberlik, nebi olmak, nebilik" },
{ eski: "Nücum", yeni: "Yıldızlar" },
{ eski: "Nükhet", yeni: "Koku" },
{ eski: "Nümayan", yeni: "Görünen, aşikâr olan, gözükücü olan, parlayan" },
{ eski: "Nümayiş", yeni: "Görünüş, gösteriş, dış görünüş, gösteri" },
{ eski: "Nüsha", yeni: "Dualı kağıt, sahife, yazılı şey" },
{ eski: "Nüşur", yeni: "Yaymalar, dağıtmalar" },
{ eski: "Pâdişâh-ı şehid", yeni: "Şehit, hükümdar" },
{ eski: "Pâk", yeni: "Temiz, saf, katıksız; hep, tamam, mübarek, kudsi" },
{ eski: "Paki şerin", yeni: "Temiz" },
{ eski: "Pâkin", yeni: "Her türlü kötülükten veya günahtan uzak durduran, temiz kişi" },
{ eski: "Pakine", yeni: "Ayrıca" },
{ eski: "Pamal", yeni: "Pullu sürüngenler, kobragiller" },
{ eski: "Pâmel", yeni: "Ezilmek, çiğnenmek" },
{ eski: "Pansör", yeni: "Hür, düşünceli" },
{ eski: "Pare", yeni: "Cüz, parça, kesinti" },
{ eski: "Pâyimâl", yeni: "Çiğnenmiş, ayak altına alınmış" },
{ eski: "Penahun", yeni: "Sığınak" },
{ eski: "Per-dar", yeni: "Asılmış, yukarı kaldırılmış" },
{ eski: "Perde-i esrar", yeni: "Sırlar perdesi" },
{ eski: "Perde-i zulmet", yeni: "Zulüm perdesi" },
{ eski: "Perran", yeni: "Uçan, uçucu" },
{ eski: "Perüka", yeni: "Berber" },
{ eski: "Pervaz", yeni: "Uçmak, kanat açmak" },
{ eski: "Pesman", yeni: "Dökülen, arta kalan" },
{ eski: "Peya", yeni: "Rütbe" },
{ eski: "Peyâm-ı vedad", yeni: "Dostluk haberi" },
{ eski: "Peyanun", yeni: "" },
{ eski: "Peyda", yeni: "Mevcud, var olan, açık, âşikâr, meydanda olan" },
{ eski: "Peyderpey", yeni: "Art arda" },
{ eski: "Peyle", yeni: "Eski kahvelerde ve evlerde duvara bitişik kerevet ve sedir" },
{ eski: "Peyma", yeni: "Yol alan, kateden, ölçen" },
{ eski: "Peyman", yeni: "And, yemin, muahede, ahitleşmek" },
{ eski: "Peymâne", yeni: "Büyük kadeh" },
{ eski: "Peytan", yeni: "Bir alayı günlerce misafir eden" },
{ eski: "Pıra", yeni: "Süsleyici, düzenleyici, donatıcı" },
{ eski: "Pış", yeni: "Huzur, ön, ileri taraf" },
{ eski: "Pinhan", yeni: "Gizli, saklı, hafi, mahfi, mestur, müstetir" },
{ eski: "Pir", yeni: "Yaşlı, ihtiyar" },
{ eski: "Pira", yeni: "Süsleyici, düzenleyici, donatıcı" },
{ eski: "Piraye", yeni: "Zinet, süs" },
{ eski: "Pişgah", yeni: "Ön, huzur, huzurunda" },
{ eski: "Pişi", yeni: "Önünü gören, ileri görüşlü" },
{ eski: "Pomak", yeni: "İslav kökenli Müslüman topluluk" },
{ eski: "Prizerin", yeni: "" },
{ eski: "Protestan", yeni: "Hristiyanlıkta reform yapılmasını isteyen, buna çalışan bir akım sonucu doğmuş olan mezhep" },
{ eski: "Pür", yeni: "Çok, dolu, çok fazla, memlu, tekrar" },
{ eski: "Ra’şedar", yeni: "Titreyen, ürken" },
{ eski: "Rab", yeni: "Tanrı" },
{ eski: "Rabıta", yeni: "İlgi, münasebet, bağlılık, mensupluk" },
{ eski: "Raci", yeni: "Geri dönen" },
{ eski: "Rahle-i tedkik", yeni: "Araştırma masası" },
{ eski: "Rahmet-i Mevla", yeni: "Allah’ın merhameti" },
{ eski: "Rahş", yeni: "Yıkamak" },
{ eski: "Rakik", yeni: "İnce" },
{ eski: "Raşe", yeni: "Titreme" },
{ eski: "Re’y", yeni: "Görme" },
{ eski: "Reca", yeni: "Ümit, istek, arzu" },
{ eski: "Refref", yeni: "Kanat çırpmak" },
{ eski: "Reh-güzarında", yeni: "Geçit, yol üstü" },
{ eski: "Rehmetullah", yeni: "Allah’ın rahmeti" },
{ eski: "Rehzen", yeni: "Yol kesen, haydut, eşkiya" },
{ eski: "Rencide", yeni: "Kırılmış, incinmiş" },
{ eski: "Reng-i giva", yeni: "Başka renk" },
{ eski: "Reng-i Hüvviyet", yeni: "Özgünlük" },
{ eski: "Reng-i Şule-i berk", yeni: "Şimşek ışığının rengi" },
{ eski: "Reng-i zilal", yeni: "Gölgeli renk" },
{ eski: "Revak", yeni: "Kemer, kubbe, çardak" },
{ eski: "Revzen", yeni: "Pencere" },
{ eski: "Reyb", yeni: "Şüphe, tereddüt" },
{ eski: "Rezil akıbet", yeni: "Kötü sonuç" },
{ eski: "Riayet", yeni: "Saygı gösterme" },
{ eski: "Ric’at", yeni: "Geri dönme, kaçış" },
{ eski: "Rical-i berhurdar", yeni: "Mesut adamlar" },
{ eski: "Rida", yeni: "Örtü, şal" },
{ eski: "Rikkat", yeni: "Acıma, incelik, yufka yüreklilik, yumuşaklık" },
{ eski: "Ru’numun", yeni: "Ortaya çıkan" },
{ eski: "Ruh", yeni: "Nefes" },
{ eski: "Ruh-ı ecdad", yeni: "Ataların ruhu" },
{ eski: "Ruh-ı edyan", yeni: "Dinlerin aslı" },
{ eski: "Ruh-ı feyyaz", yeni: "Bereket ve bolluk veren" },
{ eski: "Ruh-ı İblis", yeni: "Şeytanın ruhu" },
{ eski: "Ruh-ı lain", yeni: "Lanetli ruh" },
{ eski: "Ruh-ı sema", yeni: "Huzur ve dinginlik" },
{ eski: "Ruku", yeni: "Namazda eğilmek" },
{ eski: "Ru-numa", yeni: "Yüz gösteren" },
{ eski: "Rücu", yeni: "Geri dönme, dönüş" },
{ eski: "Sa’det", yeni: "1. Arzuların tatmin edilmesinden kaynaklanan durum. 2. Mutluluk" },
{ eski: "Sa’di", yeni: "Uğur ve mutlulukla ilgili, uğurlu" },
{ eski: "Sa’y", yeni: "1. Çalışma. 2. Hacda sefa ile merve arasında yedi defa gidip gelmek" },
{ eski: "Sa’y-i beliğ", yeni: "1. Emek harcayarak gereği gibi çalışma. 2. Güzel, düzgün söz söyleyen" },
{ eski: "Saba", yeni: "1. Sabah yeli. 2. Klasik Türk müziğinde bir birleşik makam" },
{ eski: "Sabme", yeni: "Vuruşma, çarpışma, sarsıntı" },
{ eski: "Sadâ", yeni: "1. Ses. 2. Erkek baykuş. 3. Bir böcek adı" },
{ eski: "Sadakat", yeni: "1. Sadakalar. 2. Dostluk, bağlılık" },
{ eski: "Sadda", yeni: "1. Suyu lezzetli olan örülmüş kuyu. 2. Örten, kapayan" },
{ eski: "Sadme", yeni: "Çarpışma, vurma" },
{ eski: "Sadr", yeni: "Göğüs" },
{ eski: "Sadr-ı İslam", yeni: "İslam’ın göğsü" },
{ eski: "Sâfâ", yeni: "Gönül rahatlığı, huzur" },
{ eski: "Saffet", yeni: "1. Saflık, temizlik, arılık. 2. Üstün güç" },
{ eski: "Safvet-i ruh", yeni: "Ruh temizliği" },
{ eski: "Saha", yeni: "Alan" },
{ eski: "Sahabe", yeni: "Sahipler, sahip çıkanlar" },
{ eski: "Saha-i tatbik", yeni: "Uygulama sahası" },
{ eski: "Sahib-kıran", yeni: "Her zaman başaran hükümdar" },
{ eski: "Sahne-i decur", yeni: "Karanlık sahne" },
{ eski: "Sahn-ı üryan", yeni: "Çıplak alan" },
{ eski: "Sahra", yeni: "Çöl" },
{ eski: "Sail", yeni: "1. Sual eden, soran. 2. Dilenci. 3. Denize açılmak" },
{ eski: "Saire", yeni: "Diğer" },
{ eski: "Sakf", yeni: "Dam, çatı, tavan, gökyüzü, sema" },
{ eski: "Sâkin", yeni: "Hareketsiz, kendi halinde, yalın" },
{ eski: "Sal-hurde", yeni: "Yıllanmış, yaşlı" },
{ eski: "Sâl", yeni: "Yıl" },
{ eski: "Salâh", yeni: "İyilik, rahatlık, sulh, iyileşme" },
{ eski: "Salahiyet-dar", yeni: "Yetkili" },
{ eski: "Salat", yeni: "Namaz" },
{ eski: "Salib", yeni: "Haç, haçlı" },
{ eski: "Salka", yeni: "Çuha, kadife, sırma gibi kumaşlardan yapılan kollu cepken" },
{ eski: "Saltanat", yeni: "Hükümdarlık" },
{ eski: "Samimi", yeni: "Öz, asıl" },
{ eski: "Samit", yeni: "Sessiz" },
{ eski: "Samt", yeni: "Susma" },
{ eski: "Samte", yeni: "Sessizlik" },
{ eski: "San’at", yeni: "1. Her şeyi mükemmel bir şekilde yaratan Allah’ın yüceliği. 2. Ortaya konulan üstün yaratıcılık" },
{ eski: "Sarban", yeni: "Deveci" },
{ eski: "Sarık", yeni: "Kavuk, fes" },
{ eski: "Satveti", yeni: "Ezici güç" },
{ eski: "Savaik", yeni: "Yıldırımlar" },
{ eski: "Savlet", yeni: "Hamle, hücum, saldırma" },
{ eski: "Sayan-ı merhamet", yeni: "Acınmaya layık" },
{ eski: "Saye", yeni: "Gölge" },
{ eski: "Saye-i nur", yeni: "Nurlu gölge" },
{ eski: "Sayha", yeni: "Feryat, çığlık" },
{ eski: "Sebad", yeni: "Kararlı olma durumu" },
{ eski: "Sebat", yeni: "Sabırlı olmak" },
{ eski: "Sebil", yeni: "Su dağıtılan çeşme" },
{ eski: "Sefilân", yeni: "Sefiller" },
{ eski: "Sefilâne", yeni: "Alçak bir haldeki yaşam" },
{ eski: "Sehabe-i nur", yeni: "Işıktan bir bulut" },
{ eski: "Sehabiyye", yeni: "Bulut" },
{ eski: "Sekrân", yeni: "Sarhoşlar" },
{ eski: "Selamet", yeni: "Kurtuluş" },
{ eski: "Selef", yeni: "Öncekiler" },
{ eski: "Sema", yeni: "1. Gök, gökyüzü, Allah katı. 2. Mevlevi ayin dönüşü" },
{ eski: "Seng", yeni: "Taş" },
{ eski: "Seng-i cânid", yeni: "Donuk taş" },
{ eski: "Seng-pâre", yeni: "Taş parçası" },
{ eski: "Ser-nigun", yeni: "Baş aşağı" },
{ eski: "Serab", yeni: "Çölde uzaktan su ve yeşillik gibi görünen ışık yanıltması" },
{ eski: "Serâb", yeni: "Şaşkın hale gelme" },
{ eski: "Serair", yeni: "Sırlar" },
{ eski: "Serapa", yeni: "Bütün olarak, tümüyle" },
{ eski: "Serdar", yeni: "Komutan" },
{ eski: "Serir", yeni: "Tahta karyola, kürsü, taht" },
{ eski: "Serir-i âlâ", yeni: "Yücelik tahtı" },
{ eski: "Sermedi", yeni: "Daimi, ebedi, sürekli" },
{ eski: "Sermediyet", yeni: "Daimilik, ebedilik" },
{ eski: "Servistan", yeni: "Servi bahçesi" },
{ eski: "Setre", yeni: "Örtü, perde" },
{ eski: "Setre-i bitab", yeni: "Zayıf örtü" },
{ eski: "Sevad", yeni: "Siyahlar, karalar" },
{ eski: "Sevâhil", yeni: "Kıyılar" },
{ eski: "Seyf", yeni: "Kılıç, pala" },
{ eski: "Seyr", yeni: "Gidilen yol, yürüyüş" },
{ eski: "Seyyah", yeni: "Gezgin" },
{ eski: "Seyyal", yeni: "Akan" },
{ eski: "Seyyale", yeni: "Akış" },
{ eski: "Seyyie", yeni: "Günah, kötülük, çirkin iş" },
{ eski: "Sıddık", yeni: "Gerçekçi, dürüst ve güvenilir olma" },
{ eski: "Sıyanet", yeni: "Koruma" },
{ eski: "Sima", yeni: "Yüz, çehre" },
{ eski: "Simsar", yeni: "Komisyoncu" },
{ eski: "Sin", yeni: "Gömüt, mezar" },
{ eski: "Sinâ", yeni: "1. Güçlü, kararlı. 2. Sabırlı. 3. Başkaların karşı nazik ve hoşgörülü" },
{ eski: "Sine-çâk", yeni: "Yürek parçalayan" },
{ eski: "Sine", yeni: "Göğüs, gönül, kalp" },
{ eski: "Sine-i millet", yeni: "Milletin gönlü" },
{ eski: "Sine-i münevver", yeni: "Aydınlık kucak" },
{ eski: "Sipah", yeni: "Osmanlı ordusunun ağır süvari sınıf askeri" },
{ eski: "Sipahi", yeni: "Asker" },
{ eski: "Sirac-ı ezel", yeni: "Ezeli ışık" },
{ eski: "Sirayet", yeni: "Bulaşma" },
{ eski: "Sivar", yeni: "Bileşik" },
{ eski: "Siyak", yeni: "Söz gelişi, anlatım biçimi" },
{ eski: "Sual", yeni: "Soru" },
{ eski: "Subat", yeni: "Uzun uyku biçiminde baygınlık, koma, dalgınlık, uyku" },
{ eski: "Subh", yeni: "Sabah" },
{ eski: "Subh-dem", yeni: "Sabah vakti" },
{ eski: "Sufuf", yeni: "Sıralar, saflar, diziler" },
{ eski: "Sulh", yeni: "Barış" },
{ eski: "Sun", yeni: "Sanat, tesir, etki" },
{ eski: "Suziş", yeni: "Yakma, yanma, etkileme" },
{ eski: "Suz-u güdaz", yeni: "Yanıp yakınmalar" },
{ eski: "Sücud", yeni: "Secdeler" },
{ eski: "Sükun", yeni: "Durgun" },
{ eski: "Sükut", yeni: "Susturmak, sessizlik, sakinlik" },
{ eski: "Süngü", yeni: "Tüfek namlusunun ucuna takılan delici silah" },
{ eski: "Sürat", yeni: "Hız" },
{ eski: "Sürud-ı ümit", yeni: "Ümit şarkısı" },
{ eski: "Sürur", yeni: "Sevinçli" },
{ eski: "Süveydâ", yeni: "Kalbin siyah noktası, kalpteki basiret ve idrak merkezi, ilahi aşkın tecelli ettiği yer" },
{ eski: "Şah-ı şehid", yeni: "Şehitlerin şahı" },
{ eski: "Şahika", yeni: "Zirve" },
{ eski: "Şaki", yeni: "Eşkıya, haydut" },
{ eski: "Şap", yeni: "Bir hastalık ismi" },
{ eski: "Şark", yeni: "Doğu" },
{ eski: "Şayak", yeni: "Kaba dokunmuş yün kumaş" },
{ eski: "Şayan", yeni: "Uygun" },
{ eski: "Şayeste", yeni: "Yaraşır, layık, uygun" },
{ eski: "Şeb-nisar", yeni: "Dağınık gece" },
{ eski: "Şebab", yeni: "Gençler" },
{ eski: "Şebb", yeni: "Genç" },
{ eski: "Şebistan", yeni: "Yatak odası" },
{ eski: "Şedâid", yeni: "Şiddetler" },
{ eski: "Şedait-i eyyam", yeni: "Hayatın sıkıntısı" },
{ eski: "Şedid", yeni: "Şiddetli, büyük bela" },
{ eski: "Şehadet", yeni: "Tanıklık, şehitlik" },
{ eski: "Şehamet", yeni: "Yiğitlik, cesaret, bir kişinin veya bir şeyin korunması ve savunulması" },
{ eski: "Şehbal", yeni: "Kuş kanadında bulunan en uzun tüy, kanat" },
{ eski: "Şehidan", yeni: "Şehitlik" },
{ eski: "Şehr", yeni: "Şehir" },
{ eski: "Şekl-i muhiş", yeni: "Korkunç şekil" },
{ eski: "Şems", yeni: "Güneş" },
{ eski: "Şenâ", yeni: "Övgü, övme" },
{ eski: "Şenâ’at", yeni: "Alçaklık, iğrençlik, kötülük" },
{ eski: "Şer’ar", yeni: "Savaşçı" },
{ eski: "Şer’i", yeni: "Dini kurallar" },
{ eski: "Şerait", yeni: "1. Şartlar, koşullar. 2. İslam hukuku" },
{ eski: "Şetaret", yeni: "Sevinç, neşe" },
{ eski: "Şevk", yeni: "İstek, arzu" },
{ eski: "Şevket", yeni: "Görkem, güç, büyüklük" },
{ eski: "Şevket-meab", yeni: "Şevketin, büyüklüğün bulunduğu yer" },
{ eski: "Şi’r", yeni: "Anlama, sırra erme" },
{ eski: "Şiar", yeni: "1. Ayırıcı özellik, alamet, iz. 2. Tutulacak yol, ülkü, ilke" },
{ eski: "Şikar", yeni: "Av, avlanan hayvan" },
{ eski: "Şilte", yeni: "Döşek" },
{ eski: "Şimal", yeni: "Kuzey" },
{ eski: "Şitab", yeni: "Acele etmek" },
{ eski: "Şiven", yeni: "Yas, matem" },
{ eski: "Şu’â-ı muhriki", yeni: "Yakıcı ışın" },
{ eski: "Şu’un", yeni: "İşler, fiiller" },
{ eski: "Şua", yeni: "Işın" },
{ eski: "Şule", yeni: "Aydınlık" },
{ eski: "Şumus", yeni: "Güneşler" },
{ eski: "Şüheda", yeni: "Şehitler" },
{ eski: "Şüride", yeni: "Perişan, karışık" },
{ eski: "Ta' ayyün", yeni: "Görünmek, ortaya çıkmak" },
{ eski: "Tab", yeni: "Efkâr basma işi" },
{ eski: "Tabi", yeni: "Kesinlikle, doğal olarak" },
{ eski: "tabi'", yeni: "Doğal" },
{ eski: "Tabib", yeni: "Doktor" },
{ eski: "Ta'dâd", yeni: "Sayma" },
{ eski: "Tafsil", yeni: "Bir şeyi ayrıntılarına girerek açıklama, ayrıntılı, açık, uzun anlatmak" },
{ eski: "Tağyir", yeni: "Başkalaştırma, değiştirme, bozma" },
{ eski: "Taharet", yeni: "Temizlik, nezafet" },
{ eski: "Tahattur", yeni: "Hatırlatma" },
{ eski: "Tahayyür", yeni: "Şaşırma" },
{ eski: "Tahlîs", yeni: "Kurtarma, halas etmek" },
{ eski: "Tahrir-i nüfus", yeni: "Nüfus kaydı" },
{ eski: "Takat", yeni: "Dayanma, güç, katlanma, derman" },
{ eski: "Taklid", yeni: "Düşünmeden bir başkasına uymak" },
{ eski: "Taksim", yeni: "Parçalama, ayırma, bölme" },
{ eski: "Takyid", yeni: "1. Bir mülkün üzerinde herhangi bir şehrin veya borcun olup olmadığını gösteren tapudan alınan bilgi. 2. Kaydetme" },
{ eski: "Tamik", yeni: "Derinleştirme" },
{ eski: "Tanin-i medid", yeni: "Çanakta uzun bir çınlama" },
{ eski: "Tar", yeni: "1. Saç teli. 2. Karanlık" },
{ eski: "Tarik", yeni: "Yol" },
{ eski: "Tarikat", yeni: "1. Yollar. 2. Allah’a ulaştıran yol. 3. Vasıta, meslek" },
{ eski: "Tarik-i Şam", yeni: "Şam yolları" },
{ eski: "Tarumar", yeni: "Karmakarışık, dağınık" },
{ eski: "Tasarruf", yeni: "Parayı veya tüketilebilecek herhangi bir şeyi dikkatli kullanma, idareli harcama" },
{ eski: "Tasavvuf", yeni: "Tanrımın varlığını, birliğini, niteliğini ve evrenin oluşumunu; varlık birliğiyle, yaratılanla yaratanın bir oluşu aynı kaynaktan gelişi anlayışıyla açıklayan dinsel ve felsefesi akım" },
{ eski: "Tasavvur", yeni: "Düşünme, hayal etme" },
{ eski: "Tasvir", yeni: "Göz önünde canlandırmak resmini yapmak, canlandırarak anlatma, ifade etme" },
{ eski: "Tatar", yeni: "Postacı" },
{ eski: "Tatbik", yeni: "Uygulama" },
{ eski: "Tavaf", yeni: "Etrafında dönmek" },
{ eski: "Tavazün", yeni: "Eşitlik" },
{ eski: "Tay olmak", yeni: "Bir derde ortak olmak" },
{ eski: "Tayf", yeni: "Uykuda veya karanlıkta gözde tecessüm eden şekiller, hayaller" },
{ eski: "Tazallüm", yeni: "Zulüm görmekten, acımasızlıktan yakınma, sızlanma, ağlaşma" },
{ eski: "Tazyik", yeni: "Basınç" },
{ eski: "Teaddi", yeni: "Düşmanlık, ezme" },
{ eski: "Teâli", yeni: "Yükselmek" },
{ eski: "Tebassur", yeni: "Göz açıklığı, ileri görüş" },
{ eski: "Tebessül", yeni: "Somurtma, surat asma" },
{ eski: "Tebid", yeni: "Rapor" },
{ eski: "Tebliğ", yeni: "Bildiri" },
{ eski: "Tecelli -zar-ı nur-i yezdanı", yeni: "Allah’ın ışığının tecelli ettiği yer" },
{ eski: "Tecelli", yeni: "Görünmek" },
{ eski: "Tecessüs", yeni: "Gizlice araştırma, anlama merakı" },
{ eski: "Tefekkür", yeni: "Düşünce, düşünme, düşünüş" },
{ eski: "Tefrika", yeni: "1. Fikir ayrılığı yaşama. 2. Süreli yayınlarda bölüm bölüm yayımlanan, birbirini tamamlayan yazı dizisi" },
{ eski: "Tegafül", yeni: "Anlamazlıktan gelme" },
{ eski: "Tehavvür", yeni: "Çok öfkelenme, öfkeden kabarma" },
{ eski: "Tehyic", yeni: "Coşturmak" },
{ eski: "Tekamül", yeni: "Olgunlaşma, olgunluk, ilerleme" },
{ eski: "Tekasüf", yeni: "Yoğunlaşma, sıklaşma" },
{ eski: "Teklis", yeni: "Kireç haline getirmek" },
{ eski: "Tekmil", yeni: "Tam duruma getirme, tamamlama" },
{ eski: "Tekvin", yeni: "Yoktan var etme, meydana getirmek, yaratmak" },
{ eski: "Tekvir", yeni: "Kıvırmak, sarmak, yuvarlamak" },
{ eski: "Tel’mun", yeni: "Sağlamak" },
{ eski: "Tel'in", yeni: "Lanetlemek" },
{ eski: "Temas", yeni: "İlişki ve bağ kurma" },
{ eski: "Temaşa", yeni: "Seyretme" },
{ eski: "Temayül", yeni: "Meyletmek, yöneltmek ve eğilim" },
{ eski: "Temkin", yeni: "Bir işi veya sonucu düşünerek ölçülü, hesaplı davranma" },
{ eski: "Tenha", yeni: "Yalnız, tek" },
{ eski: "Tenkid", yeni: "Eleştirme" },
{ eski: "Tenkil", yeni: "Uzaklaştırma, düşman veya zaralı kimseleri topluca ortadan kaldırma" },
{ eski: "Tenzih", yeni: "Kusur kondurmama, ayrı tutma" },
{ eski: "Ter", yeni: "Bir şeyin ilk zamanı" },
{ eski: "Terakki", yeni: "İlerleme, yükselme" },
{ eski: "Terane", yeni: "Ezgi, nağme" },
{ eski: "Tereddüt", yeni: "Şüphe duymaya başlamak" },
{ eski: "Tersim", yeni: "Resmetme" },
{ eski: "Tesaddi", yeni: "Bildirmek" },
{ eski: "Tesavir", yeni: "Tasvirler" },
{ eski: "Teslis", yeni: "Üçe çıkarma, üçleme" },
{ eski: "Teşhis", yeni: "Kişileştirme" },
{ eski: "Teşriye", yeni: "Kanun, hüküm" },
{ eski: "Tetkik", yeni: "Araştırma" },
{ eski: "Tevabi", yeni: "Tabi olanlar, bağlı olanlar, uyanlar" },
{ eski: "Tevcih", yeni: "Belli bir yöne döndürme, yönetmek" },
{ eski: "Tevekkül", yeni: "Sebeplere tevessül ettikten sonra neticesini Allah’a bırakma, Allah’a dayanma ve güvenme" },
{ eski: "Tevfik", yeni: "Allah’ın hayırlı işlerde kişiyi başarılı kılması anlamında kelam, terim" },
{ eski: "Tevkise", yeni: "Durdurmak" },
{ eski: "Tevzi", yeni: "Dağıtma, üleştirme" },
{ eski: "Teyid", yeni: "Destekleme" },
{ eski: "Tezahür", yeni: "Ortaya çıkma, belirme" },
{ eski: "Tezebzüz", yeni: "Kararlık" },
{ eski: "Tezelzüz", yeni: "Sarsılma, sallanma" },
{ eski: "Tezin", yeni: "Ezan okutmak" },
{ eski: "Tıfıl", yeni: "Küçük çocuk, bebek" },
{ eski: "Tilavet", yeni: "Kur’an-ı Kerim’i yüksek sesle, güzel ve yöntemince okuma" },
{ eski: "Timsal", yeni: "Benzeri" },
{ eski: "Tiynet", yeni: "Yaradılış, huy" },
{ eski: "Tufeylat", yeni: "1. Çocuklar, bebekler. 2. Parazitler" },
{ eski: "Tuhfe", yeni: "Hediye" },
{ eski: "Turab", yeni: "Toz ve toprak" },
{ eski: "Tüfan", yeni: "Günlerce ortalığı sellerin aldığı, çok yeğin ve yoğun olarak yağan yağmur" },
{ eski: "Türek", yeni: "1. Tepelerin arasındaki çıkıntı. 2. Kuş yuvası" },
{ eski: "Tütsü", yeni: "Büyü, ilaç yapmak ya da dinsel törenlerde çevrenin güzel kokmasını sağlamak için yakılan kokulu madde" },
{ eski: "Ukba", yeni: "Ahiret" },
{ eski: "Ukde", yeni: "Düğüm, bağ, karışık ve müşkil iş. Zorluk, zor iş. 2. Ağaçlık yer. 3. Pelteklik, kekemelik. 4. Arzu edip de ulaşamadığından dolayı içe dert olan şey" },
{ eski: "Ulema", yeni: "Bilginler, alimler, Osmanlıda ilmiye sınıf mensupları için kullanılan unvan" },
{ eski: "Ulum", yeni: "İlimler, bilimler" },
{ eski: "Ulumun", yeni: "Âlimler" },
{ eski: "Ulvi", yeni: "Yüce" },
{ eski: "Umman", yeni: "Akdeniz, okyanus" },
{ eski: "Umumen", yeni: "Bütün, hep" },
{ eski: "Unsur", yeni: "Öğe, ilke" },
{ eski: "Urefa", yeni: "Arifler" },
{ eski: "Üdeba", yeni: "Edipler, edebiyatçılar, zarif kimseler" },
{ eski: "Üm", yeni: "Ana" },
{ eski: "Ümid", yeni: "Arzu, istek" },
{ eski: "Ümmet", yeni: "Bir peygambere inanıp onun yolunu seçen kimselerin tümü" },
{ eski: "Ümmü’l kitab", yeni: "Bütün nesne ve olaylara ilişkin ilahi ve ilim ve takdirin kayıtlı bulunduğu kitap" },
{ eski: "Üryan", yeni: "Çıplak" },

{ eski: "Vaaz", yeni: "Vaizlerin cami, mescit gibi yerlerde yaptığı genellikle öğüt niteliği taşıyan dinsel konuşma" },
{ eski: "Vabeste", yeni: "Bağlı" },
{ eski: "Vahdet", yeni: "1. Yalnızlık, teklik, birliktelik. 2. Allah’a yakınlık, Allah’a ulaşma" },
{ eski: "Vahid-seray-ı", yeni: "Dinlendirici yer" },
{ eski: "Vak’a", yeni: "Olup geçen şey, hadise, olay" },
{ eski: "Vakar", yeni: "Ağırbaşlılık, temkinlilik" },
{ eski: "Vakfız", yeni: "Haberdar olmak" },
{ eski: "Vakt", yeni: "Zaman" },
{ eski: "Vaktǎ", yeni: "Ne zaman, ne vakit" },
{ eski: "Vakur", yeni: "Ağırbaşlı, temkinli" },
{ eski: "Valide", yeni: "Doğuran, ana" },
{ eski: "Vǎpesin", yeni: "Son, en sondaki, en gerideki" },
{ eski: "Varak", yeni: "Yaprak, kağıt veya kitap yaprağı" },
{ eski: "Vasıta", yeni: "1. İki şeyi birbirine bitiştiren üçüncü. 2. Aracı, arada bulunan" },
{ eski: "Vasi", yeni: "Geniş, açık, enli, bol" },
{ eski: "Vaz etmek", yeni: "Koymak, konulmak" },
{ eski: "Vaz", yeni: "Uydurmak" },
{ eski: "Vecd", yeni: "Hayranlık duymak" },
{ eski: "Vecd", yeni: "Kendinden geçecek derecede dalgınlık" },
{ eski: "Veciz", yeni: "Kısa, derli toplu" },
{ eski: "Vekil-i umurun", yeni: "İşleri gören kişi" },
{ eski: "Veled", yeni: "Evlat, erkek evlad" },
{ eski: "Velvele", yeni: "1. Şaşkınlık. 2. Gürültü, patırtı, yaygara, şamata" },
{ eski: "Vezaif", yeni: "Vazifeler, ödevler" },
{ eski: "Vezir", yeni: "Osmanlı İmparatorluğu döneminde devletin bakanlık, valilik gibi yüksek görevlerinde bulunan kimse" },
{ eski: "Viran", yeni: "Yıkık, yıkılmış" },
{ eski: "Visǎl", yeni: "Ulaşma, bitişme" },
{ eski: "Vukuf", yeni: "1. Durma, duruş. 2. Bir halde, olduğu gibi kalma, ilerleyip veya gerilememe" },
{ eski: "Vücud", yeni: "1. Bulunma, var olma, varlık. 2. İnsan veya hayvan gövdesi" },
{ eski: "Vükela", yeni: "Vekiller, kabine azası, bakanlar" },

{ eski: "Yâd", yeni: "Anma, hatırlama" },
{ eski: "Yafta", yeni: "Bir malın cinsini, fiyatını ve sairesini belirten kâğıt" },
{ eski: "Yahud", yeni: "Yahudi, Hz. Yakup’un oğlu Yahuda soyundan gelenler" },
{ eski: "Yahut", yeni: "Veya, isterseniz" },
{ eski: "Yakamoz", yeni: "Geceleri denizde, balıkların ya da sandal küreklerinin kımıldanışıyla su içinde oluşan ışıltı" },
{ eski: "Yal ü bal", yeni: "Boy pos düzgünlüğü" },
{ eski: "Yâl", yeni: "Boyun, gerdan" },
{ eski: "Yalçın", yeni: "(Dağ, kaya vb. için) çıkılamayacak denli dik ve sarp" },
{ eski: "Yâr", yeni: "Sevgili" },
{ eski: "Yârân", yeni: "Dostlar" },
{ eski: "Yâve-gülan", yeni: "Saçmasapan konuşan" },
{ eski: "Ye’s", yeni: "Ümitsizlik, elem, keder" },
{ eski: "Yed", yeni: "1. El. 2. Kuvvet, kudret, güç" },
{ eski: "Yedullah", yeni: "Allah’ın kudreti" },
{ eski: "Yegane", yeni: "Tek, biricik" },
{ eski: "Yehud", yeni: "Yahudiler" },
{ eski: "Yek-meal", yeni: "Tek anlam" },
{ eski: "Yekpare", yeni: "Tek parça, bir parçadan ibaret olan, bütün" },
{ eski: "Yel", yeni: "Pehlivan, şampiyon" },
{ eski: "Yelda", yeni: "Uzun" },
{ eski: "Yesâr", yeni: "1. Varlık, zenginlik. 2. Sol, sol taraf" },
{ eski: "Yezdân", yeni: "Zerdüştlerde hayır İlahı" },
{ eski: "Yosma", yeni: "Genç ve güzel baştan çıkarıcı kadın" },
{ eski: "Zade-i hür", yeni: "Hür oğul" },
{ eski: "Zafer-yab", yeni: "Zafer bulan, başarı gösteren, aradığı şeye erişen" },
{ eski: "Zaid", yeni: "Artan, artıran" },
{ eski: "Zairsiz mazarında", yeni: "Ziyaretçisi olmayan" },
{ eski: "Zalâm", yeni: "Karanlık" },
{ eski: "Zan", yeni: "Sanma, sanı, sezme" },
{ eski: "Zebun", yeni: "Güçsüz, zayıf, aciz" },
{ eski: "Zelil Eşhâs", yeni: "Hor, hakir, alçak, aşağı tutulan kişiler" },
{ eski: "Zelil", yeni: "Hor, hakir, alçak, aşağı tutulan, aşağılanan, horlanan" },
{ eski: "Zelzele", yeni: "1. Irgalama, sarsma. 2. Yer sarsıntısı, deprem" },
{ eski: "Zembili", yeni: "Hasırdan üretilmiş olan, yan taraflarında taşımayı kolaylaştırmak için kulp bulunan sepet" },
{ eski: "Zemzem", yeni: "Kabe yakınlarındaki mübarek su" },
{ eski: "Zeval", yeni: "1. Yerinden ayrılıp gitme. 2. Zail olma, sona erme" },
{ eski: "Zıll", yeni: "Gölge" },
{ eski: "Zillet", yeni: "Horluk, hakirlik, alçaklık, aşağılık" },
{ eski: "Zimmi", yeni: "İslam Devleti tebaasından olan ve haraç veren Hıristiyanlar, Yahudiler" },
{ eski: "Zindegan", yeni: "Zinde olanlar, diriler" },
{ eski: "Zira", yeni: "Çünkü" },
{ eski: "Zi-ruh", yeni: "Canlı" },
{ eski: "Ziya", yeni: "Işık, aydınlık" },
{ eski: "Ziya-riz", yeni: "Gizli ışık saçan, aydınlık dağıtan" },
{ eski: "Ziya-yı ilm", yeni: "İlimin ışığı" },
{ eski: "Zuhur", yeni: "Meydana çıkmak, görünür olmak" },
{ eski: "Zulimât", yeni: "Karanlık yokluklar" },
{ eski: "Zulmet", yeni: "Karanlık, yokluk" },
